# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S6gtwVqAmB7Z7fkGFtpYObnZalPdfFRI
"""

import numpy as np

print('№1')

def distance(x1, y1, x2, y2):
  dist=((x1-x2)*(x1-x2)+(y1-y2)*(y1-y2))**0.5
  return dist

print('Введите значения x1, y1, x2, y2: ')
x1=int(input())
y1=int(input())
x2=int(input())
y2=int(input())

print(distance(x1, y1, x2, y2))
print()

print('№2')

print('Введите список A через пробел: ')
A = list(map(int,input().split()))
print('Введите список B через пробел: ')
B = list(map(int,input().split()))
C = []
for i in range(0,len(A)):
  if (A[i]%2==0):
    C.append(A[i]*B[i])
  else:
    C.append(A[i]+B[i])
print(C)
print()

print('№3')
print('Введите x через пробел: ')
x = list(map(int,input().split()))
x = np.array(x)
min = x[0]
for i in range(1, len(x)-1):
  if (x[i]<min and x[i+1]==0 and x[i]!=0):
    min=x[i]
if (x[0]<min and x[1]==0):
  min = x[1]

print('Минимальный элемент:',min)
print()