# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WlKTAPwOKDfrWDe9JJOpnHgJ2gGrXDgY
"""

import numpy as np

# Задание 1

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
print(a[0,0], a[1,1], a[2,2])

# Задание 2
a[:, 1]

# Задание 3
print(a.shape)
b=a.flatten()
print(b.flatten(),b.shape)

# Задание 4
for y in range(a.shape[1]):
  print('Стобец:',y)
  for x in range(a.shape[0]):
    print(a[x,y])
for x in range(a.shape[0]):
    print('Строка:', x)
    for y in range(a.shape[1]):
        print(a[x, y])

# Задание 5
sum = 0
k = 0
l = 0
for x in range(a.shape[0]):
  for y in range(a.shape[1]):
    sum = sum + a[x, y]
    l += 1
k = sum/l
print(sum, k)
