# -*- coding: utf-8 -*-
"""home_work_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14X5wfQUI13amX66B4G9xwdtmlmQM7ARy

Задание 1
"""

import numpy as np
a = np.ones((3, 3))
a[1, 1] = 0
print(a)

"""
Задание 2"""

a = np.zeros((5, 5))
for i in range(4):
  a[i, i+1] = i + 1
print(a)

"""Задание 3"""

X = np.random.rand(5, 10)
x = 0
for i in range(5):
  for j in range(10):
    x += X[i, j]
Y = x/50
Y

"""Задание 4"""

A = np.random.rand(6, 7)
B = A.copy()
B[5] = A[2]
B[2] = A[5]
print("Оригинальный массив", A)
print("Конечный массив", B)

"""Задание 5"""

C = np.random.rand(10, 10)
С = C.astype('int32')
print(C)

"""Задание 6"""

R = np.random.rand(89, 67) # не понял как диапазон задать
s = 0
for M in range(89):
  for N in range(67):
    if R[M, N] != 0:
      s += 1
print(s)

"""Задание 7"""

m, n = input().split(' ')
m = int(m)
n = int(n)
table = np.zeros((m, n))
for M in range(m):
  for N in range(n):
    if (M + N) % 2 != 0:
      table[M, N] = 1
print(table)