# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Vr9qfwl7ljS7wSivbmJoF84_7H0K7dw
"""

import numpy as np
import math
from random import randint
a = []
x, m = map(int,input().split())
for i in range(x):
    a.append([0]*m)
for i in range(x):
    for j in range(m):
        a[i][j]=1
        if i>0:
            break
for i in range(x-1,-1,-1):
    for j in range(m-1,-1,-1):
        a[i][j]=1
        if j==m-1:
            break
for i in range(x-1,-1,-1):
    for j in range(m):
        a[i][j]=1
        if i>=1 and i<x-1:
            break
for i in a:
    print(i)

o = 0
a = []
x, m = map(int,input().split())
for i in range(x):
    a.append([0]*m)
for i in range(x):
    for j in range(m):
        if i+1==j:
            o=o+1
            a[i][j]=o
for i in a:
    print(i)

X = np.random.randint(1, 11, size=(5, 10))
Y = np.sum(X, axis = 1)/10
print(Y)

a = np.random.randint(1, 11, size=(6, 7))
for i in a:
    print(i)
print()
z = a.copy()
a[5,:] = a[2,:]
a[2,:] = z[5,:]
for i in a:
    print(i)

x, m = map(int,input().split())
a = []
for i in range(x):
    for j in range(m):
        a.append(randint(1,11))
print(a, type(a))
a = np.array(a)
print(a, type(a))

a = np.random.randint(-50, 51, size=(89, 67))
o=0
for i in range(89):
    for j in range(67):
        if a[i][j] != 0:
            o=o+1
print()
print(o)

n, m = map(int, input().split())
a = np.random.randint(0, 2, size=(n, m))
for i in range(n):
    for j in range(m):
        if (i+j)%2==0:
            a[i][j]=0
        else:
            a[i][j]=1
for i in a:
    print(i)

a = []
z = []

n = int(input())
while n>0:
    a.append(float(input()))
    n=n-1
for i in a:
    z.append(math.ceil(i))
for i in z:
    print(i)

a = list(map(int,input().split()))
b = list(map(int,input().split()))
z = []
for i in range(len(a)):
    for j in range(len(b)):
        if a[i]==b[j]:
            z.append(b[j])
z.sort()
z = np.unique(z)
print(z)