{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "Селянина_вариант_контрольной.ipynb",
      "provenance": [],
      "collapsed_sections": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "J0rCPuOouSGk"
      },
      "source": [
        "# Селянина Олеся Александровна\n",
        "\n",
        "Ссылка на данные: https://www.kaggle.com/doaaalsenani/usa-cers-dataset"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "ms4ERp0PuNvK",
        "colab": {
          "resources": {
            "http://localhost:8080/nbextensions/google.colab/files.js": {
              "data": "Ly8gQ29weXJpZ2h0IDIwMTcgR29vZ2xlIExMQwovLwovLyBMaWNlbnNlZCB1bmRlciB0aGUgQXBhY2hlIExpY2Vuc2UsIFZlcnNpb24gMi4wICh0aGUgIkxpY2Vuc2UiKTsKLy8geW91IG1heSBub3QgdXNlIHRoaXMgZmlsZSBleGNlcHQgaW4gY29tcGxpYW5jZSB3aXRoIHRoZSBMaWNlbnNlLgovLyBZb3UgbWF5IG9idGFpbiBhIGNvcHkgb2YgdGhlIExpY2Vuc2UgYXQKLy8KLy8gICAgICBodHRwOi8vd3d3LmFwYWNoZS5vcmcvbGljZW5zZXMvTElDRU5TRS0yLjAKLy8KLy8gVW5sZXNzIHJlcXVpcmVkIGJ5IGFwcGxpY2FibGUgbGF3IG9yIGFncmVlZCB0byBpbiB3cml0aW5nLCBzb2Z0d2FyZQovLyBkaXN0cmlidXRlZCB1bmRlciB0aGUgTGljZW5zZSBpcyBkaXN0cmlidXRlZCBvbiBhbiAiQVMgSVMiIEJBU0lTLAovLyBXSVRIT1VUIFdBUlJBTlRJRVMgT1IgQ09ORElUSU9OUyBPRiBBTlkgS0lORCwgZWl0aGVyIGV4cHJlc3Mgb3IgaW1wbGllZC4KLy8gU2VlIHRoZSBMaWNlbnNlIGZvciB0aGUgc3BlY2lmaWMgbGFuZ3VhZ2UgZ292ZXJuaW5nIHBlcm1pc3Npb25zIGFuZAovLyBsaW1pdGF0aW9ucyB1bmRlciB0aGUgTGljZW5zZS4KCi8qKgogKiBAZmlsZW92ZXJ2aWV3IEhlbHBlcnMgZm9yIGdvb2dsZS5jb2xhYiBQeXRob24gbW9kdWxlLgogKi8KKGZ1bmN0aW9uKHNjb3BlKSB7CmZ1bmN0aW9uIHNwYW4odGV4dCwgc3R5bGVBdHRyaWJ1dGVzID0ge30pIHsKICBjb25zdCBlbGVtZW50ID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc3BhbicpOwogIGVsZW1lbnQudGV4dENvbnRlbnQgPSB0ZXh0OwogIGZvciAoY29uc3Qga2V5IG9mIE9iamVjdC5rZXlzKHN0eWxlQXR0cmlidXRlcykpIHsKICAgIGVsZW1lbnQuc3R5bGVba2V5XSA9IHN0eWxlQXR0cmlidXRlc1trZXldOwogIH0KICByZXR1cm4gZWxlbWVudDsKfQoKLy8gTWF4IG51bWJlciBvZiBieXRlcyB3aGljaCB3aWxsIGJlIHVwbG9hZGVkIGF0IGEgdGltZS4KY29uc3QgTUFYX1BBWUxPQURfU0laRSA9IDEwMCAqIDEwMjQ7CgpmdW5jdGlvbiBfdXBsb2FkRmlsZXMoaW5wdXRJZCwgb3V0cHV0SWQpIHsKICBjb25zdCBzdGVwcyA9IHVwbG9hZEZpbGVzU3RlcChpbnB1dElkLCBvdXRwdXRJZCk7CiAgY29uc3Qgb3V0cHV0RWxlbWVudCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKG91dHB1dElkKTsKICAvLyBDYWNoZSBzdGVwcyBvbiB0aGUgb3V0cHV0RWxlbWVudCB0byBtYWtlIGl0IGF2YWlsYWJsZSBmb3IgdGhlIG5leHQgY2FsbAogIC8vIHRvIHVwbG9hZEZpbGVzQ29udGludWUgZnJvbSBQeXRob24uCiAgb3V0cHV0RWxlbWVudC5zdGVwcyA9IHN0ZXBzOwoKICByZXR1cm4gX3VwbG9hZEZpbGVzQ29udGludWUob3V0cHV0SWQpOwp9CgovLyBUaGlzIGlzIHJvdWdobHkgYW4gYXN5bmMgZ2VuZXJhdG9yIChub3Qgc3VwcG9ydGVkIGluIHRoZSBicm93c2VyIHlldCksCi8vIHdoZXJlIHRoZXJlIGFyZSBtdWx0aXBsZSBhc3luY2hyb25vdXMgc3RlcHMgYW5kIHRoZSBQeXRob24gc2lkZSBpcyBnb2luZwovLyB0byBwb2xsIGZvciBjb21wbGV0aW9uIG9mIGVhY2ggc3RlcC4KLy8gVGhpcyB1c2VzIGEgUHJvbWlzZSB0byBibG9jayB0aGUgcHl0aG9uIHNpZGUgb24gY29tcGxldGlvbiBvZiBlYWNoIHN0ZXAsCi8vIHRoZW4gcGFzc2VzIHRoZSByZXN1bHQgb2YgdGhlIHByZXZpb3VzIHN0ZXAgYXMgdGhlIGlucHV0IHRvIHRoZSBuZXh0IHN0ZXAuCmZ1bmN0aW9uIF91cGxvYWRGaWxlc0NvbnRpbnVlKG91dHB1dElkKSB7CiAgY29uc3Qgb3V0cHV0RWxlbWVudCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKG91dHB1dElkKTsKICBjb25zdCBzdGVwcyA9IG91dHB1dEVsZW1lbnQuc3RlcHM7CgogIGNvbnN0IG5leHQgPSBzdGVwcy5uZXh0KG91dHB1dEVsZW1lbnQubGFzdFByb21pc2VWYWx1ZSk7CiAgcmV0dXJuIFByb21pc2UucmVzb2x2ZShuZXh0LnZhbHVlLnByb21pc2UpLnRoZW4oKHZhbHVlKSA9PiB7CiAgICAvLyBDYWNoZSB0aGUgbGFzdCBwcm9taXNlIHZhbHVlIHRvIG1ha2UgaXQgYXZhaWxhYmxlIHRvIHRoZSBuZXh0CiAgICAvLyBzdGVwIG9mIHRoZSBnZW5lcmF0b3IuCiAgICBvdXRwdXRFbGVtZW50Lmxhc3RQcm9taXNlVmFsdWUgPSB2YWx1ZTsKICAgIHJldHVybiBuZXh0LnZhbHVlLnJlc3BvbnNlOwogIH0pOwp9CgovKioKICogR2VuZXJhdG9yIGZ1bmN0aW9uIHdoaWNoIGlzIGNhbGxlZCBiZXR3ZWVuIGVhY2ggYXN5bmMgc3RlcCBvZiB0aGUgdXBsb2FkCiAqIHByb2Nlc3MuCiAqIEBwYXJhbSB7c3RyaW5nfSBpbnB1dElkIEVsZW1lbnQgSUQgb2YgdGhlIGlucHV0IGZpbGUgcGlja2VyIGVsZW1lbnQuCiAqIEBwYXJhbSB7c3RyaW5nfSBvdXRwdXRJZCBFbGVtZW50IElEIG9mIHRoZSBvdXRwdXQgZGlzcGxheS4KICogQHJldHVybiB7IUl0ZXJhYmxlPCFPYmplY3Q+fSBJdGVyYWJsZSBvZiBuZXh0IHN0ZXBzLgogKi8KZnVuY3Rpb24qIHVwbG9hZEZpbGVzU3RlcChpbnB1dElkLCBvdXRwdXRJZCkgewogIGNvbnN0IGlucHV0RWxlbWVudCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKGlucHV0SWQpOwogIGlucHV0RWxlbWVudC5kaXNhYmxlZCA9IGZhbHNlOwoKICBjb25zdCBvdXRwdXRFbGVtZW50ID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQob3V0cHV0SWQpOwogIG91dHB1dEVsZW1lbnQuaW5uZXJIVE1MID0gJyc7CgogIGNvbnN0IHBpY2tlZFByb21pc2UgPSBuZXcgUHJvbWlzZSgocmVzb2x2ZSkgPT4gewogICAgaW5wdXRFbGVtZW50LmFkZEV2ZW50TGlzdGVuZXIoJ2NoYW5nZScsIChlKSA9PiB7CiAgICAgIHJlc29sdmUoZS50YXJnZXQuZmlsZXMpOwogICAgfSk7CiAgfSk7CgogIGNvbnN0IGNhbmNlbCA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2J1dHRvbicpOwogIGlucHV0RWxlbWVudC5wYXJlbnRFbGVtZW50LmFwcGVuZENoaWxkKGNhbmNlbCk7CiAgY2FuY2VsLnRleHRDb250ZW50ID0gJ0NhbmNlbCB1cGxvYWQnOwogIGNvbnN0IGNhbmNlbFByb21pc2UgPSBuZXcgUHJvbWlzZSgocmVzb2x2ZSkgPT4gewogICAgY2FuY2VsLm9uY2xpY2sgPSAoKSA9PiB7CiAgICAgIHJlc29sdmUobnVsbCk7CiAgICB9OwogIH0pOwoKICAvLyBXYWl0IGZvciB0aGUgdXNlciB0byBwaWNrIHRoZSBmaWxlcy4KICBjb25zdCBmaWxlcyA9IHlpZWxkIHsKICAgIHByb21pc2U6IFByb21pc2UucmFjZShbcGlja2VkUHJvbWlzZSwgY2FuY2VsUHJvbWlzZV0pLAogICAgcmVzcG9uc2U6IHsKICAgICAgYWN0aW9uOiAnc3RhcnRpbmcnLAogICAgfQogIH07CgogIGNhbmNlbC5yZW1vdmUoKTsKCiAgLy8gRGlzYWJsZSB0aGUgaW5wdXQgZWxlbWVudCBzaW5jZSBmdXJ0aGVyIHBpY2tzIGFyZSBub3QgYWxsb3dlZC4KICBpbnB1dEVsZW1lbnQuZGlzYWJsZWQgPSB0cnVlOwoKICBpZiAoIWZpbGVzKSB7CiAgICByZXR1cm4gewogICAgICByZXNwb25zZTogewogICAgICAgIGFjdGlvbjogJ2NvbXBsZXRlJywKICAgICAgfQogICAgfTsKICB9CgogIGZvciAoY29uc3QgZmlsZSBvZiBmaWxlcykgewogICAgY29uc3QgbGkgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaScpOwogICAgbGkuYXBwZW5kKHNwYW4oZmlsZS5uYW1lLCB7Zm9udFdlaWdodDogJ2JvbGQnfSkpOwogICAgbGkuYXBwZW5kKHNwYW4oCiAgICAgICAgYCgke2ZpbGUudHlwZSB8fCAnbi9hJ30pIC0gJHtmaWxlLnNpemV9IGJ5dGVzLCBgICsKICAgICAgICBgbGFzdCBtb2RpZmllZDogJHsKICAgICAgICAgICAgZmlsZS5sYXN0TW9kaWZpZWREYXRlID8gZmlsZS5sYXN0TW9kaWZpZWREYXRlLnRvTG9jYWxlRGF0ZVN0cmluZygpIDoKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgJ24vYSd9IC0gYCkpOwogICAgY29uc3QgcGVyY2VudCA9IHNwYW4oJzAlIGRvbmUnKTsKICAgIGxpLmFwcGVuZENoaWxkKHBlcmNlbnQpOwoKICAgIG91dHB1dEVsZW1lbnQuYXBwZW5kQ2hpbGQobGkpOwoKICAgIGNvbnN0IGZpbGVEYXRhUHJvbWlzZSA9IG5ldyBQcm9taXNlKChyZXNvbHZlKSA9PiB7CiAgICAgIGNvbnN0IHJlYWRlciA9IG5ldyBGaWxlUmVhZGVyKCk7CiAgICAgIHJlYWRlci5vbmxvYWQgPSAoZSkgPT4gewogICAgICAgIHJlc29sdmUoZS50YXJnZXQucmVzdWx0KTsKICAgICAgfTsKICAgICAgcmVhZGVyLnJlYWRBc0FycmF5QnVmZmVyKGZpbGUpOwogICAgfSk7CiAgICAvLyBXYWl0IGZvciB0aGUgZGF0YSB0byBiZSByZWFkeS4KICAgIGxldCBmaWxlRGF0YSA9IHlpZWxkIHsKICAgICAgcHJvbWlzZTogZmlsZURhdGFQcm9taXNlLAogICAgICByZXNwb25zZTogewogICAgICAgIGFjdGlvbjogJ2NvbnRpbnVlJywKICAgICAgfQogICAgfTsKCiAgICAvLyBVc2UgYSBjaHVua2VkIHNlbmRpbmcgdG8gYXZvaWQgbWVzc2FnZSBzaXplIGxpbWl0cy4gU2VlIGIvNjIxMTU2NjAuCiAgICBsZXQgcG9zaXRpb24gPSAwOwogICAgZG8gewogICAgICBjb25zdCBsZW5ndGggPSBNYXRoLm1pbihmaWxlRGF0YS5ieXRlTGVuZ3RoIC0gcG9zaXRpb24sIE1BWF9QQVlMT0FEX1NJWkUpOwogICAgICBjb25zdCBjaHVuayA9IG5ldyBVaW50OEFycmF5KGZpbGVEYXRhLCBwb3NpdGlvbiwgbGVuZ3RoKTsKICAgICAgcG9zaXRpb24gKz0gbGVuZ3RoOwoKICAgICAgY29uc3QgYmFzZTY0ID0gYnRvYShTdHJpbmcuZnJvbUNoYXJDb2RlLmFwcGx5KG51bGwsIGNodW5rKSk7CiAgICAgIHlpZWxkIHsKICAgICAgICByZXNwb25zZTogewogICAgICAgICAgYWN0aW9uOiAnYXBwZW5kJywKICAgICAgICAgIGZpbGU6IGZpbGUubmFtZSwKICAgICAgICAgIGRhdGE6IGJhc2U2NCwKICAgICAgICB9LAogICAgICB9OwoKICAgICAgbGV0IHBlcmNlbnREb25lID0gZmlsZURhdGEuYnl0ZUxlbmd0aCA9PT0gMCA/CiAgICAgICAgICAxMDAgOgogICAgICAgICAgTWF0aC5yb3VuZCgocG9zaXRpb24gLyBmaWxlRGF0YS5ieXRlTGVuZ3RoKSAqIDEwMCk7CiAgICAgIHBlcmNlbnQudGV4dENvbnRlbnQgPSBgJHtwZXJjZW50RG9uZX0lIGRvbmVgOwoKICAgIH0gd2hpbGUgKHBvc2l0aW9uIDwgZmlsZURhdGEuYnl0ZUxlbmd0aCk7CiAgfQoKICAvLyBBbGwgZG9uZS4KICB5aWVsZCB7CiAgICByZXNwb25zZTogewogICAgICBhY3Rpb246ICdjb21wbGV0ZScsCiAgICB9CiAgfTsKfQoKc2NvcGUuZ29vZ2xlID0gc2NvcGUuZ29vZ2xlIHx8IHt9OwpzY29wZS5nb29nbGUuY29sYWIgPSBzY29wZS5nb29nbGUuY29sYWIgfHwge307CnNjb3BlLmdvb2dsZS5jb2xhYi5fZmlsZXMgPSB7CiAgX3VwbG9hZEZpbGVzLAogIF91cGxvYWRGaWxlc0NvbnRpbnVlLAp9Owp9KShzZWxmKTsK",
              "ok": true,
              "headers": [
                [
                  "content-type",
                  "application/javascript"
                ]
              ],
              "status": 200,
              "status_text": ""
            }
          },
          "base_uri": "https://localhost:8080/",
          "height": 72
        },
        "outputId": "4e88256e-cf39-4b56-b3d2-30801f951a4e"
      },
      "source": [
        "from google.colab import files\n",
        "uploaded = files.upload()"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/html": [
              "\n",
              "     <input type=\"file\" id=\"files-17513d21-0010-4545-a393-3752f7bcef9b\" name=\"files[]\" multiple disabled\n",
              "        style=\"border:none\" />\n",
              "     <output id=\"result-17513d21-0010-4545-a393-3752f7bcef9b\">\n",
              "      Upload widget is only available when the cell has been executed in the\n",
              "      current browser session. Please rerun this cell to enable.\n",
              "      </output>\n",
              "      <script src=\"/nbextensions/google.colab/files.js\"></script> "
            ],
            "text/plain": [
              "<IPython.core.display.HTML object>"
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Saving USA_cars_datasets.csv to USA_cars_datasets.csv\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "IpALDAFtw2bv"
      },
      "source": [
        "# 1. Считайте DataFrame\n",
        "\n",
        "# ваш код тут"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 204
        },
        "id": "l0nNif0jh4FG",
        "outputId": "13e5e1e5-b57e-49da-a9b2-6e76a10cd214"
      },
      "source": [
        "import pandas as pd\n",
        "\n",
        "df = pd.read_csv('USA_cars_datasets.csv')\n",
        "df.head()"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>Unnamed: 0</th>\n",
              "      <th>price</th>\n",
              "      <th>brand</th>\n",
              "      <th>model</th>\n",
              "      <th>year</th>\n",
              "      <th>title_status</th>\n",
              "      <th>mileage</th>\n",
              "      <th>color</th>\n",
              "      <th>vin</th>\n",
              "      <th>lot</th>\n",
              "      <th>state</th>\n",
              "      <th>country</th>\n",
              "      <th>condition</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>0</td>\n",
              "      <td>6300</td>\n",
              "      <td>toyota</td>\n",
              "      <td>cruiser</td>\n",
              "      <td>2008</td>\n",
              "      <td>clean vehicle</td>\n",
              "      <td>274117.0</td>\n",
              "      <td>black</td>\n",
              "      <td>jtezu11f88k007763</td>\n",
              "      <td>159348797</td>\n",
              "      <td>new jersey</td>\n",
              "      <td>usa</td>\n",
              "      <td>10 days left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>1</td>\n",
              "      <td>2899</td>\n",
              "      <td>ford</td>\n",
              "      <td>se</td>\n",
              "      <td>2011</td>\n",
              "      <td>clean vehicle</td>\n",
              "      <td>190552.0</td>\n",
              "      <td>silver</td>\n",
              "      <td>2fmdk3gc4bbb02217</td>\n",
              "      <td>166951262</td>\n",
              "      <td>tennessee</td>\n",
              "      <td>usa</td>\n",
              "      <td>6 days left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>2</td>\n",
              "      <td>5350</td>\n",
              "      <td>dodge</td>\n",
              "      <td>mpv</td>\n",
              "      <td>2018</td>\n",
              "      <td>clean vehicle</td>\n",
              "      <td>39590.0</td>\n",
              "      <td>silver</td>\n",
              "      <td>3c4pdcgg5jt346413</td>\n",
              "      <td>167655728</td>\n",
              "      <td>georgia</td>\n",
              "      <td>usa</td>\n",
              "      <td>2 days left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>3</td>\n",
              "      <td>25000</td>\n",
              "      <td>ford</td>\n",
              "      <td>door</td>\n",
              "      <td>2014</td>\n",
              "      <td>clean vehicle</td>\n",
              "      <td>64146.0</td>\n",
              "      <td>blue</td>\n",
              "      <td>1ftfw1et4efc23745</td>\n",
              "      <td>167753855</td>\n",
              "      <td>virginia</td>\n",
              "      <td>usa</td>\n",
              "      <td>22 hours left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>4</td>\n",
              "      <td>27700</td>\n",
              "      <td>chevrolet</td>\n",
              "      <td>1500</td>\n",
              "      <td>2018</td>\n",
              "      <td>clean vehicle</td>\n",
              "      <td>6654.0</td>\n",
              "      <td>red</td>\n",
              "      <td>3gcpcrec2jg473991</td>\n",
              "      <td>167763266</td>\n",
              "      <td>florida</td>\n",
              "      <td>usa</td>\n",
              "      <td>22 hours left</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>"
            ],
            "text/plain": [
              "   Unnamed: 0  price      brand  ...       state  country      condition\n",
              "0           0   6300     toyota  ...  new jersey      usa   10 days left\n",
              "1           1   2899       ford  ...   tennessee      usa    6 days left\n",
              "2           2   5350      dodge  ...     georgia      usa    2 days left\n",
              "3           3  25000       ford  ...    virginia      usa  22 hours left\n",
              "4           4  27700  chevrolet  ...     florida      usa  22 hours left\n",
              "\n",
              "[5 rows x 13 columns]"
            ]
          },
          "metadata": {},
          "execution_count": 4
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "d_N5MRFsw2n7"
      },
      "source": [
        "# 2. Проведите анализ DataFrame\n",
        "# - Какая размерность данных?\n",
        "# - Какие типы переменных представленны в наборе данных?\n",
        "# - Есть пропуски в данных? Если да, удалите строки, в которых есть пропуски\n",
        "\n",
        "# ваш код тут"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "naGRO0VNiHR9",
        "outputId": "16bce700-8f41-4a4d-c437-33708c3d8768"
      },
      "source": [
        "df.shape"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "(2499, 13)"
            ]
          },
          "metadata": {},
          "execution_count": 5
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "vb-W58_1iIWI",
        "outputId": "a99a9d53-c28a-4709-d199-c96bff24b879"
      },
      "source": [
        "df.info()"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "<class 'pandas.core.frame.DataFrame'>\n",
            "RangeIndex: 2499 entries, 0 to 2498\n",
            "Data columns (total 13 columns):\n",
            " #   Column        Non-Null Count  Dtype  \n",
            "---  ------        --------------  -----  \n",
            " 0   Unnamed: 0    2499 non-null   int64  \n",
            " 1   price         2499 non-null   int64  \n",
            " 2   brand         2499 non-null   object \n",
            " 3   model         2499 non-null   object \n",
            " 4   year          2499 non-null   int64  \n",
            " 5   title_status  2499 non-null   object \n",
            " 6   mileage       2499 non-null   float64\n",
            " 7   color         2499 non-null   object \n",
            " 8   vin           2499 non-null   object \n",
            " 9   lot           2499 non-null   int64  \n",
            " 10  state         2499 non-null   object \n",
            " 11  country       2499 non-null   object \n",
            " 12  condition     2499 non-null   object \n",
            "dtypes: float64(1), int64(4), object(8)\n",
            "memory usage: 253.9+ KB\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "2p1YKR_4ib9l",
        "outputId": "60e9b6fd-0395-4da9-8509-c898f86ca2ce"
      },
      "source": [
        "df.isna().sum()"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "Unnamed: 0      0\n",
              "price           0\n",
              "brand           0\n",
              "model           0\n",
              "year            0\n",
              "title_status    0\n",
              "mileage         0\n",
              "color           0\n",
              "vin             0\n",
              "lot             0\n",
              "state           0\n",
              "country         0\n",
              "condition       0\n",
              "dtype: int64"
            ]
          },
          "metadata": {},
          "execution_count": 45
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 419
        },
        "id": "NykS7h8ci1nW",
        "outputId": "c9f04fbe-169a-47d0-bc34-bc8b9813aa79"
      },
      "source": [
        "df.dropna(axis=0, how='any') # ну на всякий)"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>Unnamed: 0</th>\n",
              "      <th>price</th>\n",
              "      <th>brand</th>\n",
              "      <th>model</th>\n",
              "      <th>year</th>\n",
              "      <th>title_status</th>\n",
              "      <th>mileage</th>\n",
              "      <th>color</th>\n",
              "      <th>vin</th>\n",
              "      <th>lot</th>\n",
              "      <th>state</th>\n",
              "      <th>country</th>\n",
              "      <th>condition</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>0</td>\n",
              "      <td>6300</td>\n",
              "      <td>toyota</td>\n",
              "      <td>cruiser</td>\n",
              "      <td>2008</td>\n",
              "      <td>clean vehicle</td>\n",
              "      <td>274117.0</td>\n",
              "      <td>black</td>\n",
              "      <td>jtezu11f88k007763</td>\n",
              "      <td>159348797</td>\n",
              "      <td>new jersey</td>\n",
              "      <td>usa</td>\n",
              "      <td>10 days left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>1</td>\n",
              "      <td>2899</td>\n",
              "      <td>ford</td>\n",
              "      <td>se</td>\n",
              "      <td>2011</td>\n",
              "      <td>clean vehicle</td>\n",
              "      <td>190552.0</td>\n",
              "      <td>silver</td>\n",
              "      <td>2fmdk3gc4bbb02217</td>\n",
              "      <td>166951262</td>\n",
              "      <td>tennessee</td>\n",
              "      <td>usa</td>\n",
              "      <td>6 days left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>2</td>\n",
              "      <td>5350</td>\n",
              "      <td>dodge</td>\n",
              "      <td>mpv</td>\n",
              "      <td>2018</td>\n",
              "      <td>clean vehicle</td>\n",
              "      <td>39590.0</td>\n",
              "      <td>silver</td>\n",
              "      <td>3c4pdcgg5jt346413</td>\n",
              "      <td>167655728</td>\n",
              "      <td>georgia</td>\n",
              "      <td>usa</td>\n",
              "      <td>2 days left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>3</td>\n",
              "      <td>25000</td>\n",
              "      <td>ford</td>\n",
              "      <td>door</td>\n",
              "      <td>2014</td>\n",
              "      <td>clean vehicle</td>\n",
              "      <td>64146.0</td>\n",
              "      <td>blue</td>\n",
              "      <td>1ftfw1et4efc23745</td>\n",
              "      <td>167753855</td>\n",
              "      <td>virginia</td>\n",
              "      <td>usa</td>\n",
              "      <td>22 hours left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>4</td>\n",
              "      <td>27700</td>\n",
              "      <td>chevrolet</td>\n",
              "      <td>1500</td>\n",
              "      <td>2018</td>\n",
              "      <td>clean vehicle</td>\n",
              "      <td>6654.0</td>\n",
              "      <td>red</td>\n",
              "      <td>3gcpcrec2jg473991</td>\n",
              "      <td>167763266</td>\n",
              "      <td>florida</td>\n",
              "      <td>usa</td>\n",
              "      <td>22 hours left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>...</th>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2494</th>\n",
              "      <td>2494</td>\n",
              "      <td>7800</td>\n",
              "      <td>nissan</td>\n",
              "      <td>versa</td>\n",
              "      <td>2019</td>\n",
              "      <td>clean vehicle</td>\n",
              "      <td>23609.0</td>\n",
              "      <td>red</td>\n",
              "      <td>3n1cn7ap9kl880319</td>\n",
              "      <td>167722715</td>\n",
              "      <td>california</td>\n",
              "      <td>usa</td>\n",
              "      <td>1 days left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2495</th>\n",
              "      <td>2495</td>\n",
              "      <td>9200</td>\n",
              "      <td>nissan</td>\n",
              "      <td>versa</td>\n",
              "      <td>2018</td>\n",
              "      <td>clean vehicle</td>\n",
              "      <td>34553.0</td>\n",
              "      <td>silver</td>\n",
              "      <td>3n1cn7ap5jl884088</td>\n",
              "      <td>167762225</td>\n",
              "      <td>florida</td>\n",
              "      <td>usa</td>\n",
              "      <td>21 hours left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2496</th>\n",
              "      <td>2496</td>\n",
              "      <td>9200</td>\n",
              "      <td>nissan</td>\n",
              "      <td>versa</td>\n",
              "      <td>2018</td>\n",
              "      <td>clean vehicle</td>\n",
              "      <td>31594.0</td>\n",
              "      <td>silver</td>\n",
              "      <td>3n1cn7ap9jl884191</td>\n",
              "      <td>167762226</td>\n",
              "      <td>florida</td>\n",
              "      <td>usa</td>\n",
              "      <td>21 hours left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2497</th>\n",
              "      <td>2497</td>\n",
              "      <td>9200</td>\n",
              "      <td>nissan</td>\n",
              "      <td>versa</td>\n",
              "      <td>2018</td>\n",
              "      <td>clean vehicle</td>\n",
              "      <td>32557.0</td>\n",
              "      <td>black</td>\n",
              "      <td>3n1cn7ap3jl883263</td>\n",
              "      <td>167762227</td>\n",
              "      <td>florida</td>\n",
              "      <td>usa</td>\n",
              "      <td>2 days left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2498</th>\n",
              "      <td>2498</td>\n",
              "      <td>9200</td>\n",
              "      <td>nissan</td>\n",
              "      <td>versa</td>\n",
              "      <td>2018</td>\n",
              "      <td>clean vehicle</td>\n",
              "      <td>31371.0</td>\n",
              "      <td>silver</td>\n",
              "      <td>3n1cn7ap4jl884311</td>\n",
              "      <td>167762228</td>\n",
              "      <td>florida</td>\n",
              "      <td>usa</td>\n",
              "      <td>21 hours left</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "<p>2499 rows × 13 columns</p>\n",
              "</div>"
            ],
            "text/plain": [
              "      Unnamed: 0  price      brand  ...       state  country      condition\n",
              "0              0   6300     toyota  ...  new jersey      usa   10 days left\n",
              "1              1   2899       ford  ...   tennessee      usa    6 days left\n",
              "2              2   5350      dodge  ...     georgia      usa    2 days left\n",
              "3              3  25000       ford  ...    virginia      usa  22 hours left\n",
              "4              4  27700  chevrolet  ...     florida      usa  22 hours left\n",
              "...          ...    ...        ...  ...         ...      ...            ...\n",
              "2494        2494   7800     nissan  ...  california      usa    1 days left\n",
              "2495        2495   9200     nissan  ...     florida      usa  21 hours left\n",
              "2496        2496   9200     nissan  ...     florida      usa  21 hours left\n",
              "2497        2497   9200     nissan  ...     florida      usa    2 days left\n",
              "2498        2498   9200     nissan  ...     florida      usa  21 hours left\n",
              "\n",
              "[2499 rows x 13 columns]"
            ]
          },
          "metadata": {},
          "execution_count": 8
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "Om-CW2KYw2to"
      },
      "source": [
        "# 3. Создайте функцию, которая принимает DataFrame\n",
        "# и возвращает кортеж состоящий из кортежей:\n",
        "# ( (год, ср. цена авто этого года), (год, ср. авто этого года), ...)\n",
        "# т е пару год и средняя цена автомобилей этого года\n",
        "\n",
        "# ваш код тут"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "eXUnQZ8zqPjV",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "f11e8695-fb89-4fa1-afe8-608350e71322"
      },
      "source": [
        "from statistics import mean\n",
        "\n",
        "\n",
        "def fun(df):\n",
        "  dt = {}\n",
        "  for i in range(2499):\n",
        "    if df['year'][i] not in dt:\n",
        "      dt[df['year'][i]] = [df['price'][i]]\n",
        "    else:\n",
        "      dt[df['year'][i]].append(df['price'][i])\n",
        "  k = []\n",
        "  for e in (dt):\n",
        "    k.append(tuple([e, mean(dt[e])]))\n",
        "  k = tuple(k)\n",
        "  return k\n",
        "tup = fun(df)\n",
        "tup"
      ],
      "execution_count": 46,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "((2008, 3750),\n",
              " (2011, 8737),\n",
              " (2018, 19058),\n",
              " (2014, 11817),\n",
              " (2010, 2167),\n",
              " (2017, 18596),\n",
              " (2009, 2041),\n",
              " (2013, 8764),\n",
              " (2015, 15563),\n",
              " (2020, 25083),\n",
              " (2016, 18280),\n",
              " (1973, 29800),\n",
              " (2003, 2547),\n",
              " (2019, 24025),\n",
              " (2002, 700),\n",
              " (2000, 43),\n",
              " (2001, 1485),\n",
              " (2005, 2387),\n",
              " (2012, 7657),\n",
              " (2006, 3005),\n",
              " (2007, 648),\n",
              " (1998, 6),\n",
              " (2004, 1362),\n",
              " (1994, 12),\n",
              " (1997, 0),\n",
              " (1996, 0),\n",
              " (1999, 25),\n",
              " (1984, 25),\n",
              " (1995, 0),\n",
              " (1993, 0))"
            ]
          },
          "metadata": {},
          "execution_count": 46
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "cmO-YBN-xcgw"
      },
      "source": [
        "# 4. Постройте график:\n",
        "# - гистограмма количества записей для каждого типа год\n",
        "# - гистограмма количества записей для каждого типа\tstate\n",
        "\n",
        "# Графики должны располагать на РАЗНЫХ координатных плоскостях\n",
        "# У графика должен быть заголовок, подписаны оси, а также легенда (т е графики должны быть подписаны)\n",
        "\n",
        "# ваш код тут"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 281
        },
        "id": "tPkwy03djSg_",
        "outputId": "559603aa-68c7-4de9-db38-a1f1dc8618cd"
      },
      "source": [
        "import matplotlib.pyplot as plt\n",
        "\n",
        "y = []\n",
        "x = []\n",
        "for i in df['year'].unique():\n",
        "  x += [i]\n",
        "for i in pd.unique(df['year']).tolist():\n",
        "  y += [len(df[df['year'] == i])]\n",
        "\n",
        "fig, ax = plt.subplots()\n",
        "ax.bar(x, y)\n",
        "plt.title('Распределение типа year')\n",
        "plt.show()"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXcAAAEICAYAAACktLTqAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+WH4yJAAAVo0lEQVR4nO3de7TdZX3n8fcHAijXcImIIRDqddRqpRml44x1ZKpcbGHNqMvRKiIOdkatt6pRO6OzFIuzrIjLLi0VbRytl6KtGbFavFCnw4AGbyixGhgkSYMECBevGPnOH7/nyPZwDjnnZJ9zkifv11pnnd9+nuf32893753P/u1n77OTqkKS1Je9FnsCkqTxM9wlqUOGuyR1yHCXpA4Z7pLUIcNdkjpkuEtShwz3ziW5LslPkvwwyQ+S/GWSAxd7XpLml+G+Z/jdqjoQOB5YBfzxIs9He5AkSxZ7Dnsiw30PUlWbgb8DHgmQ5Mwk65PckeTaJC8cHZ/ktCRfT3J7kmuSnNTaL03y0/Zq4IftlcF1I/tdl+S1Sa5Osi3J+5PcZ6T/qe24tya5LMmjJl3vB5PcOXLsTSN9+yV5W5Lr2yuR9yS570j/yiQ1MrdfJHlB69sryepWy81JPpbksEn7LZk0jze27SdOmscz2vgXjLQ9v92e25J8NsmxU90PSb4xUttdI3N9XeuvJA9q28e0cR+cpr4fJvn5yDwPTfKpJFvbPD6V5Ohp5vGqJB+f1PbOJOe37UOSXJhkS5LNSd6cZO/W98AkX2i3401JPpRk6aTHwGuSfBP4kQG/8Az3PUiSFcApwNda043AU4GDgTOB85Ic38Y+FvgA8CpgKfAE4LqRw724qg5srwh+d4qrezbwFOCBwENorxaSPAZ4H/BC4HDgz4G1SfYbnSpwTjv2yZOOe2473m8ADwKWA/9tpH/iMX1I2/9/j/S9BDgd+G3gAcA24M+mmPu9SrIP8CZgy0jbacDrgH8PLGvX++Gp9q+qR4/U9s8Tt2NVvWWK4W8Cbp6ifenI7f/Rkfa9gPcDxwLHAD8B3jVNKR8ETpoI5RbAz2S43wH+EtjOcDs/BngyMPFkFuBPGG7HfwGsAN446fj/ETi1zXX7NHPQPDHc9wx/m+RW4B+BfwDeAlBVF1fVNTX4B+DvgX/T9jkLeF9VXVJVd1XV5qr6ziyu811VtbGqbgHOYfiHDnA28OdVdUVV/aKq1gA/A04Y2fe+wJ2TD5gkbf+XV9UtVXVHq+WZI8P2Be6qql9MMac/AF5fVZuq6mcMYfS0OZxVvhC4AvjupGP/SVWtb0H2FuA3pjt7n4n2iua3gDUz3aeqbq6qj1fVj9vtcw7Dk9lUY7cAXwKe3ppOAm6qqiuTHMlwIvCyqvpRVd0InEe7ratqQ3ts/KyqtgJvn+J63tkeAz+ZcdEaG18q7RlOr6rPTW5McjLwBoYz4b2A/YGrWvcK4NM7cZ0bR7a/z3CGB8MZ5RlJXjLSv+9IP8D9ga1THHNZm+OVQ84Dwxnk3iNjDmM4I5/KscDfJLlrpO0XwJEjl28aOfb+tCfCX15ZchDwaoYnwdHQPRY4P8mfjg5neGXx/WnmsyNvBf4rw5nxjCTZnyGETwIObc0HJdl7mie8NcB/Bv4C+H3gf7b2Y4F9gC0jt8detPu1hf/5DLfDQa1v8u2+ES0az9z3UG0Z5OPA24Ajq2opQ5hP/EveyLCkMlcrRraPAf555LjnVNXSkZ/9q+rDbV77MLwn8I0pjnkTwzLDI0b2nVh+mfAQfvWMetRG4ORJ132f9l7EhCMm+oCPTXGMVwEfq6rJgb0ReOGkY9+3qi6bZi478iSGZaup5nBvXgk8FHhcVR3MsJwGd9+vk/0t8Kgkj2RYovtQa9/I8IrqiJF6Dq6qR7T+twAF/Hq7nt+f4jr8ytlFZLjvufYF9mM4Q97ezuKfPNJ/IXBmkhPbG5HLkzxsFsd/UZKj2xuWr+fudeG/AP4gyeMyOCDJqe2MGIa1/xuAdZMPWFV3tf3PS3I/gDavp7TtFcBLGQJrKu8BzplYKkmyrK2Vz9RBbX7nTHPs1yZ5RDv2IUmePsW4mXoj8Oqa/XdyH8TwBHhru+3fcG+Dq+qnwEXAXwFfrqrrW/sWhmW6P01ycHsMPDDJxNLLQcAPgduSLGd40tMuxHDfQ7X12D9kODPcBjwLWDvS/2Xam6zAbQxr9bNZP/4rhnC4FrgGeHM77jrgPzG8ybcN2AA8DyDJsxneYD0OuCPJDxk+3fOAJO9px31N2+fyJLcDn2M4UwX4LHBpm/NUzm81/n2SO4DLgcfNoqaDGdaR77HsU1V/w7CM8pE2r29xzzeDZ+NrVXXpHPZ7B8N7Fjcx1PeZGeyzBvh17l6SmfBchpOAqxnuq4uAo1rff2f4aO1twMXAJ+YwV82j+J91aNwyfCzyBVOt8+9gv+cBK6vqjZPajwbeXFXPG9MUNSLJMcB3gPtX1e2LPR+Nh2fu2pX8CJgqXLYDtyzwXPYISfYCXgF8xGDvi5+W0S6jqv56mvYbGAJIY5TkAOAHDJ/mOWmRp6Mxc1lGkjrksowkdWiXWJY54ogjauXKlYs9DUnarVx55ZU3VdWyqfp2iXBfuXIl69bd42PNkqR7kWTav352WUaSOmS4S1KHDHdJ6pDhLkkdMtwlqUOGuyR1yHCXpA4Z7pLUIcNdkjq0S/yFqiT1YuXqi+/Rdt25py74PDxzl6QOGe6S1CHDXZI6ZLhLUocMd0nqkOEuSR0y3CWpQ4a7JHXIcJekDhnuktQhw12SOmS4S1KHDHdJ6pDhLkkdMtwlqUOGuyR1yHCXpA7NKNyTvDzJt5N8K8mHk9wnyXFJrkiyIclHk+zbxu7XLm9o/SvnswBJ0j3tMNyTLAf+EFhVVY8E9gaeCbwVOK+qHgRsA85qu5wFbGvt57VxkqQFNNNlmSXAfZMsAfYHtgBPAi5q/WuA09v2ae0yrf/EJBnPdCVJM7HDcK+qzcDbgOsZQv024Erg1qra3oZtApa37eXAxrbv9jb+8MnHTXJ2knVJ1m3dunVn65AkjZjJssyhDGfjxwEPAA4ATtrZK66qC6pqVVWtWrZs2c4eTpI0YibLMv8O+H9VtbWqfg58Ang8sLQt0wAcDWxu25uBFQCt/xDg5rHOWpJ0r2YS7tcDJyTZv62dnwhcDXwReFobcwbwyba9tl2m9X+hqmp8U5Yk7chM1tyvYHhj9KvAVW2fC4DXAK9IsoFhTf3CtsuFwOGt/RXA6nmYtyTpXizZ8RCoqjcAb5jUfC3w2CnG/hR4+s5PTZI0V/6FqiR1yHCXpA4Z7pLUIcNdkjpkuEtShwx3SeqQ4S5JHTLcJalDhrskdchwl6QOGe6S1CHDXZI6ZLhLUocMd0nqkOEuSR0y3CWpQ4a7JHXIcJekDhnuktQhw12SOmS4S1KHDHdJ6pDhLkkdMtwlqUOGuyR1yHCXpA4Z7pLUIcNdkjpkuEtShwx3SeqQ4S5JHTLcJalDhrskdchwl6QOGe6S1CHDXZI6ZLhLUodmFO5Jlia5KMl3kqxP8ltJDktySZLvtd+HtrFJ8s4kG5J8M8nx81uCJGmymZ65nw98pqoeBjwaWA+sBj5fVQ8GPt8uA5wMPLj9nA28e6wzliTt0A7DPckhwBOACwGq6s6quhU4DVjThq0BTm/bpwEfqMHlwNIkR4195pKkac3kzP04YCvw/iRfS/LeJAcAR1bVljbmBuDItr0c2Diy/6bWJklaIDMJ9yXA8cC7q+oxwI+4ewkGgKoqoGZzxUnOTrIuybqtW7fOZldJ0g7MJNw3AZuq6op2+SKGsP/BxHJL+31j698MrBjZ/+jW9iuq6oKqWlVVq5YtWzbX+UuSprDDcK+qG4CNSR7amk4ErgbWAme0tjOAT7bttcBz26dmTgBuG1m+kSQtgCUzHPcS4ENJ9gWuBc5keGL4WJKzgO8Dz2hjPw2cAmwAftzGSpIW0IzCvaq+DqyaouvEKcYW8KKdnJckaSf4F6qS1CHDXZI6ZLhLUocMd0nqkOEuSR0y3CWpQ4a7JHXIcJekDhnuktQhw12SOmS4S1KHDHdJ6pDhLkkdMtwlqUOGuyR1yHCXpA4Z7pLUIcNdkjpkuEtShwx3SeqQ4S5JHTLcJalDhrskdchwl6QOGe6S1CHDXZI6ZLhLUocMd0nqkOEuSR0y3CWpQ4a7JHXIcJekDhnuktQhw12SOmS4S1KHDHdJ6pDhLkkdMtwlqUMzDvckeyf5WpJPtcvHJbkiyYYkH02yb2vfr13e0PpXzs/UJUnTmc2Z+0uB9SOX3wqcV1UPArYBZ7X2s4Btrf28Nk6StIBmFO5JjgZOBd7bLgd4EnBRG7IGOL1tn9Yu0/pPbOMlSQtkpmfu7wBeDdzVLh8O3FpV29vlTcDytr0c2AjQ+m9r439FkrOTrEuybuvWrXOcviRpKkt2NCDJU4Ebq+rKJE8c1xVX1QXABQCrVq2qcR1XkhbCytUX36PtunNPXYSZTG2H4Q48Hvi9JKcA9wEOBs4HliZZ0s7OjwY2t/GbgRXApiRLgEOAm8c+c0nStHa4LFNVr62qo6tqJfBM4AtV9Wzgi8DT2rAzgE+27bXtMq3/C1XlmbkkLaCd+Zz7a4BXJNnAsKZ+YWu/EDi8tb8CWL1zU5QkzdZMlmV+qaouBS5t29cCj51izE+Bp49hbpK0qKZaV4dda219Ov6FqiR1yHCXpA4Z7pLUIcNdkjpkuEtShwx3SeqQ4S5JHTLcJalDhrskdchwl6QOGe6S1CHDXZI6ZLhLUocMd0nqkOEuSR0y3CWpQ4a7JHXIcJekDhnuktQhw12SOmS4S1KHDHdJ6pDhLkkdMtwlqUOGuyR1yHCXpA4Z7pLUIcNdkjpkuEtShwx3SeqQ4S5JHTLcJalDhrskdchwl6QOGe6S1CHDXZI6ZLhLUod2GO5JViT5YpKrk3w7yUtb+2FJLknyvfb70NaeJO9MsiHJN5McP99FSJJ+1UzO3LcDr6yqhwMnAC9K8nBgNfD5qnow8Pl2GeBk4MHt52zg3WOftSTpXu0w3KtqS1V9tW3fAawHlgOnAWvasDXA6W37NOADNbgcWJrkqLHPXJI0rSWzGZxkJfAY4ArgyKra0rpuAI5s28uBjSO7bWptW0baSHI2w5k9xxxzzCynLUnjs3L1xfdou+7cUxdhJuMz43BPciDwceBlVXV7kl/2VVUlqdlccVVdAFwAsGrVqlntK0lz0WOIT2dGn5ZJsg9DsH+oqj7Rmn8wsdzSft/Y2jcDK0Z2P7q1SZIWyEw+LRPgQmB9Vb19pGstcEbbPgP45Ej7c9unZk4AbhtZvpEkLYCZLMs8HngOcFWSr7e21wHnAh9LchbwfeAZre/TwCnABuDHwJljnbEkaYd2GO5V9Y9Apuk+cYrxBbxoJ+clSdoJ/oWqJHXIcJekDhnuktQhw12SOmS4S1KHDHdJ6pDhLkkdMtwlqUOGuyR1yHCXpA4Z7pLUIcNdkjpkuEtShwx3SeqQ4S5JHTLcJalDhrskdWgm/82eJO02Vq6++B5t15176iLMZHF55i5JHTLcJalDhrskdcg1d0m7JdfW751n7pLUIcNdkjrksoykXZrLL3Pjmbskdchwl6QOGe6S1CHDXZI6ZLhLUof8tIwkLZCF/OSPZ+6S1CHDXZI6ZLhLUocMd0nqkG+oSlp0fsXA+HnmLkkd8sxd0px4tr1rm5dwT3IScD6wN/Deqjp3Pq5H0q5puuD3CWHhjD3ck+wN/BnwO8Am4CtJ1lbV1eO+LmlPdm9BOdtwnap9R/to1zYfZ+6PBTZU1bUAST4CnAYY7lowcwmkcQbiXObl2a7GKVU13gMmTwNOqqoXtMvPAR5XVS+eNO5s4Ox28aHAP411IruHI4CbFnsSi8j699z69+TaYXz1H1tVy6bqWLQ3VKvqAuCCxbr+XUGSdVW1arHnsVisf8+tf0+uHRam/vn4KORmYMXI5aNbmyRpgcxHuH8FeHCS45LsCzwTWDsP1yNJmsbYl2WqanuSFwOfZfgo5Puq6tvjvp5O7NHLUlj/nlz/nlw7LED9Y39DVZK0+Pz6AUnqkOEuSR0y3McsyfuS3JjkWyNtj07yf5NcleR/JTm4te+TZE1rX5/ktSP7nJTkn5JsSLJ6MWqZi1nWv2+S97f2byR54sg+v9naNyR5Z5IsQjmzkmRFki8muTrJt5O8tLUfluSSJN9rvw9t7Wm1bUjyzSTHjxzrjDb+e0nOWKyaZmMO9T+sPS5+luSPJh1rt3r8z6H2Z7f7/KoklyV59MixxlN7Vfkzxh/gCcDxwLdG2r4C/Hbbfj7wprb9LOAjbXt/4DpgJcMb0dcAvwbsC3wDePhi1zYP9b8IeH/bvh9wJbBXu/xl4AQgwN8BJy92bTOo/Sjg+LZ9EPBd4OHA/wBWt/bVwFvb9imttrRar2jthwHXtt+Htu1DF7u+eaj/fsC/BM4B/mjkOLvd438Otf+rifsUOHnkvh9b7Z65j1lVfQm4ZVLzQ4Avte1LgP8wMRw4IMkS4L7AncDtjHyFQ1XdCUx8hcMub5b1Pxz4QtvvRuBWYFWSo4CDq+ryGh7xHwBOn++576yq2lJVX23bdwDrgeUM992aNmwNd9dyGvCBGlwOLG21PwW4pKpuqaptDLfZSQtYypzMtv6qurGqvgL8fNKhdrvH/xxqv6zdtwCXM/w9EIyxdsN9YXybu++gp3P3H3ldBPwI2AJcD7ytqm5heFBsHNl/U2vbXU1X/zeA30uyJMlxwG+2vuUMNU/Y7epPshJ4DHAFcGRVbWldNwBHtu3p7ufd/v6fYf3T2a3rn0PtZzG8goMx1m64L4znA/8lyZUML9nubO2PBX4BPAA4Dnhlkl9bnCnOq+nqfx/Dg3cd8A7gMobbY7eW5EDg48DLqur20b72SqTrzx/vyfXPtvYk/5Yh3F8z7rn4n3UsgKr6DvBkgCQPASa+0u9ZwGeq6ufAjUn+D7CK4Zm7m69wmK7+qtoOvHxiXJLLGNYqt3H3y1TYjepPsg/DP+4PVdUnWvMPkhxVVVvassuNrX26r+rYDDxxUvul8znvcZll/dPZLb/CZLa1J3kU8F6G95Nubs1jq90z9wWQ5H7t917AHwPvaV3XA09qfQcwvKn2HTr7Cofp6k+yf6ubJL8DbK+qq9vL2NuTnNA+JfNc4JOLM/uZa3O9EFhfVW8f6VoLTHzi5QzurmUt8Nz2qZkTgNta7Z8Fnpzk0Pbpiie3tl3aHOqfzm73+J9t7UmOAT4BPKeqvjsyfny1L/a7zL39AB9mWEP/OcOSw1nASxnOSL8LnMvdfxl8IPDXDGvSVwOvGjnOKW38NcDrF7uueap/JcNXPa8HPsfw9aUTx1kFfKvV/66JfXblH+BfM7zs/ibw9fZzCnA48Hnge63Ow9r4MPzHNtcAVwGrRo71fGBD+zlzsWubp/rv3x4jtzO8mb6J4Y303e7xP4fa38vwCnVi7LqRY42ldr9+QJI65LKMJHXIcJekDhnuktQhw12SOmS4S1KHDHdJ6pDhLkkd+v+wZEu1XDpbrQAAAABJRU5ErkJggg==\n",
            "text/plain": [
              "<Figure size 432x288 with 1 Axes>"
            ]
          },
          "metadata": {
            "needs_background": "light"
          }
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 281
        },
        "id": "uHNhlDcfpn-G",
        "outputId": "6f30bcb9-27d1-4d36-e5a7-2f2ec73e316b"
      },
      "source": [
        "import matplotlib.pyplot as plt\n",
        "\n",
        "y = []\n",
        "x = []\n",
        "for i in df['state'].unique():\n",
        "  x += [i]\n",
        "for i in pd.unique(df['state']).tolist():\n",
        "  y += [len(df[df['state'] == i])]\n",
        "\n",
        "fig, ax = plt.subplots()\n",
        "ax.bar(x, y)\n",
        "plt.title('Распределение типа state')\n",
        "plt.show()"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAX0AAAEICAYAAACzliQjAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+WH4yJAAAgAElEQVR4nO3df7wfVX3n8dc7IfwSFDCR8iM1FNGt7NbII1Vcuy2VbQW0RbeWal0ExSItWO1iK1i3ZVVatrXQurQqCiXdFoEVURZ/gVSq1IKEnwIBiRAkISQhgSTkF8m9n/5xPuP35Mv33vu9uffm3mTez8fj+/jOnJk5c2bmzGfOnPn+UERgZmbtMG2yC2BmZjuOg76ZWYs46JuZtYiDvplZizjom5m1iIO+mVmLOOibmbWIg/4uStJiSRslPStpuaTLJe0z2eWyqU3SeZL+cRTzHyNpyUSWycaXg/6u7dciYh/gKGAe8NFJLo+ZTTIH/RaIiKXA14H/CCDp3ZIWSlon6RFJ76vnl3SipLslrZX0I0nHZfrNkjbl3cOzeSexuFpusaRzJT0g6WlJfy9pz2r6mzPfZyR9T9LPda33HyU9V+W9pJq2h6RPSvpx3rl8RtJe1fQ5kqIq24Ck9+a0aZLOyW1ZJelqSQd0LbdbVznOy+FjuspxUs7/3irtPbk/n5b0TUkv7XUcJN1TbdtgVdaP5PSQ9LIc/umc7x+H2L5nJW2pyrm/pOslrcxyXC/p0KHqhKQPS1qadeAhScfmcf4I8FuZ/z3D1RdJL6DUq4OrMh083P62yeeg3wKSZgMnAHdl0grgzcALgXcDF0k6Kud9DfAPwB8C+wG/CCyusjsrIvbJO4hf67G6dwJvBA4HXk7eXUh6NXAZ8D7gxcBngesk7VEXFTg/8z6+K98LMr+5wMuAQ4A/qaY3dflFufx3q2nvB94C/BJwMPA08Lc9yj4sSTOAjwPLqrQTKYHyvwGzcr1f6LV8RLyq2rYnmv0YEX/WY/aPA6t6pO9X7f+rqvRpwN8DLwV+GtgIXDzEdrwCOAv4+YjYl3K8FkfEN4A/A67KdbwqF+lZXyJifY9teYJx2t82MRz0d21flvQMcAvwL5QTmoj4akT8KIp/AW4A/ksucxpwWUTcGBGDEbE0Ih4cxTovjojHI2I1cD7wjkw/HfhsRNwWEQMRMR/YDBxdLbsX8Fx3hpKUy/9BRKyOiHW5LW+vZtsdGIyIgR5lOgP444hYEhGbgfOAt9Wt+z69D7gN+GFX3n8eEQsjYmuWa+5Qrf1+5B3Q64D5/S4TEasi4pqI2JD753xK0O1lANgDeKWkGRGxOCJ+NEzew9WXXsZrf9sEcNDftb0lIvaLiJdGxO9FxEYAScdLulXS6rwonADMzGVmA0MGgD48Xg0/RmnpQWmBnp1dO8/kemdX0wF+CljZI89ZwN7AHdWy38j0xgGUFmUvLwWurZZdSAl8B1bzPFVNP6k7A0n7An8E/M8eef9Ntexqyh3LIUOUpR//O9ezpd8FJO0t6bOSHpO0FvgOsJ+k6d3zRsQi4IOUYLxC0pWSDu6er8p7uPrSSz/72yaJg37LZHfKNcAngQMjYj/ga5RABSVoHz6GVcyuhn8aeKLK9/y8CDWvvSPiC1muGZRnDvf0yPMpSnfFkdWyTTdO4+Vs2wKvPQ4c37XuPfNZR2NmMw24ukcefwhcHRGP9cj7fV157xUR3xuiLCN5A6X7q1cZhnM28ArgtRHxQkq3HHSO6zYi4oqI+AVKgA7KhYYc/ok+6kuvn+ntZ3/bJHHQb5/dKbf2K4Gtko4HfrWafinw7nywN03SIZL+wyjyP1PSofng7o/p9Dt/DjhD0mtVvEDSm7IFDaWv+ElgQXeGETGYy18k6SUAWa435vBs4APAl4co02eA85suF0mzsi++X/tm+c4fIu9zJR2Zeb9I0m+OIu9u5wF/FKP/zfN9KRfGZ3Lf/+lQM0p6haQ3ZEDflMsN5uTlwBxJTWwYqb4sB14s6UVV2lj3t00gB/2Wyf7e36e0JJ8Gfhu4rpr+ffJhHbCG8ixgNP3TV1D6fB+hdBN9IvNdAPwO5eHi08Ai4FQASe+kPNg9DFgn6Vk6nwr5TOb74Vzm1uy++BalZQvwTeDmLHMvf5PbeIOkdcCtwGtHsU0vBD4VEc/rPoqIaymt5CuzXPfx/IfQo3FXRNy8Hcv9NeWZyFOU7fvGMPPuQXkw/hTlQvsS4Nyc9v/yfZWkO/uoLw9SHlw/kt05BzP2/W0TSP4TFRsvKh/ffG9EfGuUy50KzImI87rSDwU+ERGnjlMRzVrPLX2bCtYDa3ukb6U8GDWzceKWvo2b7W3pm9mO46BvZtYi7t4xM2uRKfENuZkzZ8acOXMmuxhmZjuVO+6446mImDXynB1TIujPmTOHBQue9/FsMzMbhqTuLwuOyN07ZmYt4qBvZtYiDvpmZi3ioG9m1iIO+mZmLTJi0Je0p6Tvq/zV2/2S/lemHybpNkmLJF0lafdM3yPHF+X0ORO7CWZm1q9+WvqbgTfkX6fNBY6TdDTllwUvioiXUX5977Sc/zTg6Uy/iM7vdJuZ2SQbMejnX6Q9m6Mz8hWUP3v4YqbPp/wnJsCJdP7m7YvAsfl3d2ZmNsn66tOXNF3S3ZQ/SL6R8jvpz+R/ggIsofP3cIeQf5mX09dQ/gmoO8/TJS2QtGDlyl7/kGdmZuOtr2/k5p9Nz5W0H3AtMJp/Uhoqz0uASwDmzZvnX30bZ3PO+erz0hZf8KZJKImZTSWj+vRORDwDfBt4HeVPl5uLxqFA8/+XS8n/Sc3pLwJWjUtpzcxsTPr59M6sbOEjaS/gVyj/bv9t4G052ynAV3L4uhwnp//zdvzfp5mZTYB+uncOAuZLmk65SFwdEddLeoDyv6CfAO6i/KE2+f5/JS2i/OvR2yeg3GZmth1GDPoRcS/w6h7pjwCv6ZG+CfjNcSmdmZmNK38j18ysRRz0zcxaxEHfzKxFHPTNzFrEQd/MrEUc9M3MWsRB38ysRRz0zcxaxEHfzKxFHPTNzFrEQd/MrEUc9M3MWsRB38ysRRz0zcxaxEHfzKxFHPTNzFrEQd/MrEUc9M3MWsRB38ysRRz0zcxaxEHfzKxFHPTNzFrEQd/MrEUc9M3MWsRB38ysRUYM+pJmS/q2pAck3S/pA5l+nqSlku7O1wnVMudKWiTpIUlvnMgNMDOz/u3WxzxbgbMj4k5J+wJ3SLoxp10UEZ+sZ5b0SuDtwJHAwcC3JL08IgbGs+BmZjZ6I7b0I2JZRNyZw+uAhcAhwyxyInBlRGyOiEeBRcBrxqOwZmY2NqPq05c0B3g1cFsmnSXpXkmXSdo/0w4BHq8WW8LwFwkzM9tB+g76kvYBrgE+GBFrgU8DhwNzgWXAX41mxZJOl7RA0oKVK1eOZlEzM9tOfQV9STMoAf+fIuJLABGxPCIGImIQ+BydLpylwOxq8UMzbRsRcUlEzIuIebNmzRrLNpiZWZ9GfJArScClwMKIuLBKPygiluXoW4H7cvg64ApJF1Ie5B4BfH9cSz2J5pzz1Z7piy940w4uiZnZ6PXz6Z3XAycDP5B0d6Z9BHiHpLlAAIuB9wFExP2SrgYeoHzy50x/csfMbGoYMehHxC2Aekz62jDLnA+cP4ZymZnZBPA3cs3MWsRB38ysRRz0zcxaxEHfzKxFHPTNzFrEQd/MrEUc9M3MWsRB38ysRRz0zcxaxEHfzKxFHPTNzFrEQd/MrEUc9M3MWsRB38ysRRz0zcxaxEHfzKxFHPTNzFrEQd/MrEUc9M3MWsRB38ysRUb8Y3Tr35xzvtozffEFb9rBJTEz680tfTOzFnHQNzNrEQd9M7MWcdA3M2sRB30zsxYZMehLmi3p25IekHS/pA9k+gGSbpT0cL7vn+mS9ClJiyTdK+moid4IMzPrTz8t/a3A2RHxSuBo4ExJrwTOAW6KiCOAm3Ic4HjgiHydDnx63EttZmbbZcSgHxHLIuLOHF4HLAQOAU4E5uds84G35PCJwD9EcSuwn6SDxr3kZmY2aqPq05c0B3g1cBtwYEQsy0lPAgfm8CHA49ViSzKtO6/TJS2QtGDlypWjLLaZmW2PvoO+pH2Aa4APRsTaelpEBBCjWXFEXBIR8yJi3qxZs0azqJmZbae+gr6kGZSA/08R8aVMXt502+T7ikxfCsyuFj8008zMbJL18+kdAZcCCyPiwmrSdcApOXwK8JUq/V35KZ6jgTVVN5CZmU2ifn5w7fXAycAPJN2daR8BLgCulnQa8BhwUk77GnACsAjYALx7XEtsZmbbbcSgHxG3ABpi8rE95g/gzDGWy8zMJoC/kWtm1iL+Pf0dxL+1b2ZTgVv6ZmYt4qBvZtYiDvpmZi3ioG9m1iIO+mZmLeKgb2bWIg76ZmYt4qBvZtYiDvpmZi3ioG9m1iIO+mZmLeKgb2bWIg76ZmYt4qBvZtYi/mll20avn4D2zz+b7Trc0jczaxEHfTOzFnHQNzNrEQd9M7MWcdA3M2sRB30zsxZx0DczaxEHfTOzFnHQNzNrkRGDvqTLJK2QdF+Vdp6kpZLuztcJ1bRzJS2S9JCkN05Uwc3MbPT6aelfDhzXI/2iiJibr68BSHol8HbgyFzm7yRNH6/CmpnZ2IwY9CPiO8DqPvM7EbgyIjZHxKPAIuA1YyifmZmNo7H06Z8l6d7s/tk/0w4BHq/mWZJpzyPpdEkLJC1YuXLlGIphZmb92t6g/2ngcGAusAz4q9FmEBGXRMS8iJg3a9as7SyGmZmNxnYF/YhYHhEDETEIfI5OF85SYHY166GZZmZmU8B2/Z6+pIMiYlmOvhVoPtlzHXCFpAuBg4EjgO+PuZS7uF6/YQ/+HXszG38jBn1JXwCOAWZKWgL8KXCMpLlAAIuB9wFExP2SrgYeALYCZ0bEwMQU3czMRmvEoB8R7+iRfOkw858PnD+WQpmZ2cTwN3LNzFrEQd/MrEUc9M3MWsRB38ysRRz0zcxaxEHfzKxFHPTNzFrEQd/MrEUc9M3MWsRB38ysRRz0zcxaxEHfzKxFHPTNzFrEQd/MrEUc9M3MWmS7/jnLbFfjfy+ztnBL38ysRRz0zcxaxEHfzKxFHPTNzFrED3LNWqDXg2o/pG4nt/TNzFrEQd/MrEUc9M3MWsRB38ysRUYM+pIuk7RC0n1V2gGSbpT0cL7vn+mS9ClJiyTdK+moiSy8mZmNTj8t/cuB47rSzgFuiogjgJtyHOB44Ih8nQ58enyKaWZm42HEoB8R3wFWdyWfCMzP4fnAW6r0f4jiVmA/SQeNV2HNzGxstrdP/8CIWJbDTwIH5vAhwOPVfEsyzczMpoAxP8iNiABitMtJOl3SAkkLVq5cOdZimJlZH7Y36C9vum3yfUWmLwVmV/MdmmnPExGXRMS8iJg3a9as7SyGmZmNxvYG/euAU3L4FOArVfq78lM8RwNrqm4gMzObZCP+9o6kLwDHADMlLQH+FLgAuFrSacBjwEk5+9eAE4BFwAbg3RNQZjMz204jBv2IeMcQk47tMW8AZ461UGa24/jH2NrF38g1M2sR/7RyD/6/VDPbVbmlb2bWIg76ZmYtstN377grxsysfzt90DezXYc/STTx3L1jZtYiDvpmZi3ioG9m1iIO+mZmLeKgb2bWIg76ZmYt4qBvZtYiDvpmZi3ioG9m1iL+Rq7ZCPxTH7YrcUvfzKxFHPTNzFrEQd/MrEXcp99C/iVDs/ZyS9/MrEUc9M3MWsRB38ysRRz0zcxaxA9yd2L+0pCZjZZb+mZmLTKmlr6kxcA6YADYGhHzJB0AXAXMARYDJ0XE02MrppmZjYfxaOn/ckTMjYh5OX4OcFNEHAHclONmZjYFTESf/onAMTk8H7gZ+PAErGdM3B9uZm001pZ+ADdIukPS6Zl2YEQsy+EngQN7LSjpdEkLJC1YuXLlGIthZmb9GGtL/xciYqmklwA3SnqwnhgRISl6LRgRlwCXAMybN6/nPGZmNr7G1NKPiKX5vgK4FngNsFzSQQD5vmKshTQzs/Gx3S19SS8ApkXEuhz+VeBjwHXAKcAF+f6V8Sio2Vj5OY7Z2Lp3DgSuldTkc0VEfEPS7cDVkk4DHgNOGnsxzcxsPGx30I+IR4BX9UhfBRw7lkKZmdnE8DdyzcxaxEHfzKxFHPTNzFrEQd/MrEUc9M3MWsRB38ysRfwnKjYuen3xyV96Mpt6HPSnOH+L1MzGk7t3zMxaxEHfzKxF3L1jU5afE+y8fOymrl066Ls/3Caa65jtbHbpoG9mY+MW+67HffpmZi3ilr7ZLmJn6Wry3cPkckvfzKxFHPTNzFrE3TtmtsvaWbq8diS39M3MWsQtfeubH8CNjluZNhU56JtNAl8QbLI46JvZTs93of1z0LcJ5xPSbOpw0LdJ5QuC2Y7loG+7FPeVmw3PH9k0M2uRCWvpSzoO+BtgOvD5iLhgotZl7bKrt+Z3lu3b2bvmtnc/7yzHZygTEvQlTQf+FvgVYAlwu6TrIuKBiVifme36duRFZiIC+1S5WExUS/81wKKIeARA0pXAiYCDvtkYTJXAYb3tDMdHETH+mUpvA46LiPfm+MnAayPirGqe04HTc/QVwEPjsOqZwFOeNqnTpko5PG3qT5sq5Zhq00bjpRExa1RLRMS4v4C3Ufrxm/GTgYsnYl1d613gaZM7baqUw9Om/rSpUo6pNm2iXxP16Z2lwOxq/NBMMzOzSTRRQf924AhJh0naHXg7cN0ErcvMzPo0IQ9yI2KrpLOAb1I+snlZRNw/EevqcomnTfq0qVIOT5v606ZKOabatAk1IQ9yzcxsavI3cs3MWsRB38ysRaZE0Je0n6Tf285l50n6VJ/zHizpi11pvy9poaSlki4eYrkbJJ3dvbykX5d0jqRTJf1Q0nsknSHpXZIGJP2GpLsl3SXp8FFu1xxJ93WlfUzSf833syX952ra5fn9iO7hz0s6U9I5OX6zpHm91pXbsbBZtmudP9l2SVdKeria53pJX6jnz+FTJR2cw2+R9Mqudf72MGW6vKscx0i6vho/T9KHqvFT83VOc1x67UtJiyXNrPK8N4/XNnWwKZ+kh4eqF9W8Z0h6V5XnBkknSvpzSU/W25rz9F1ne6zrSkl/Iel7PbbtGEkrcls+Ienrmb7N/hgm78WSZjbHullHn+Wak+u+S9I9fS7zbL5/TNI7JS2q90sez4u7lmnKeIOkJ+p86nwzzxWSruua1nObJN3S7K+hytqrnlbTP1/X70wbdVwbah3ddWZ78v6JyfqsaNdnVucA9+2gde3WNf4g8FLgVODi7ulDla+eD3gPsBB4W5U2APwf4KOjKJuAaf3sE+BjwIeq8cub9dfDPZa7GZjXa/tyHyzstWyzvZQH89uUDTivLkuvdXWXCTgGuH6YMg05f7XOPxpuu3odP2AxMDOHj63K0L1NxwDXN/ViFPXpDcAG4C+A83O/blP2Mdbfu4H5Q2zb89bTXb4R8v7Jvun3HGrqLPAzua3foM/PoAPP9tqOKu3d3fu+VxnrfOrxfrcn570F+PpwZR2ujo1U70axTF/roHPO9n18f7LseFTEPgq3EPgccD9wA7BXTjs8K8lqSpBcCHwyx2/PjRoEfjHz2QBcVecDXJrLLgFWARuBh4HNwMpMfxzYRPkG3ADwQ2Br5h2ZtrEab15bcr4Y4dXkNZjLLMn0wcw7qvdB4Lkq3+b9uR55NsMPU37Coklvpm0ZoswDmd9mYE0uW2/rYPV6NpeJap46z6bcS3ts90DXvIM8vzzd+Q31apYdAG7qKuMWYG2P/AfzmNb5PAesyG3vXseTPda5tdr+ervq/b+2xzzNcdzStdwtXfstch9374NNwPoh9vlz1fGr8/7REPu8Oe69jsNKOnVmoGv6Fp5f7waBR6vtX9+1LwYp52n3cht6bGOvfbYu90f38XmkR57d+TfLbKrSl/XYf4PVPBuAi3rM80y1XXX6Voauw93H+rncni3VOuvzaqBrvBnemK8NeUwfpNTZxVU+91Hi1C15DDdm2c6mNHgWZ/5PUxqr11Bi5u3A64eLyTuqe+cI4G8j4kjKzv6NTL8EeD9wVG7EMkowX09pYZ1LOeFOBnanBPk/r/L5EPBLOfwlSqvjNuDFufyLKBeVdZQW6p6UnfsgJQBsplwQvpXTAtiHTuVbn+9QDk7zBbN/yzw3U4LOF3Ldy4AbgRm53K25LvL9sZzvh5SD+ySdC8QM4LcpBw3KgR7M4Yez/FAO9FW5zNO5f6BUik2UVtfWKm06sB/w40yblvvr0irv4zK/y+gEV3K4qSOP5/u3KJW1yf/ean0X0anYzb6KXPeqHF9D+eLeYOZzV5Z7A/A9yr4/Jufbkmmrgb1z3zXHYyvlGCjzWk35iPAM4IVVmdZT9vMTdDyWr/oiuTbXvSy3eUWVR3PMoBzv7+cy04CrM30T5WQ8Osevo9PIeDLfT8ntXJfl/FLuQ3L641mmC3P6dOCXs+zTgNNyv4rO8W72xwZgeQ6vzmWeBf41xzcBTfdDUD6uvSXzXVXtn+XAC+gEtt2zHN+lE2QezPIBvA7473TqzJpqm7bmtm+i1GdRzvM11fKn5PshOW9jflWmJZRzbffM82Y6F4D51bpOpnOO3ZXpm4CfBe6h3H015YRyvKGc2/W51nQX3ZNl3ZR5rqTTSFqb23Au8M85/SngjBzeSmnUPpHjNwGfyOUfpBzH6cAPKOffTODrwHdyPfsCH6R8sfVh4Ndz2z5GOWbrgAcjYn/gAOCiiPh5Smz9PMPZQS39h6vxDwMfpQTXjZTb1QdyuGnpP005AZZTTsIfUH7aYV1XPl+ldAOsAl5PqTQrKJVhI51W0xY6J/di4Cw6V/QVlBO0GV9J54rfVIYmOKyv8qxbAU2L4ZKsDD/O8dU5PlDl0bRUmlbA5mr63bmOeloTNB/M5TcBX8syDFBO9uYEfZpOwB2gBPf11bS6lfOeTH8I+Pshtqtuhf5lDr88y9Vs88PVfPXy9TbfWx2PQUoA7W5hNcs0aU9TgusTwD/lcdmS72soJ9h6OkFmoDr2a6pjVR+7+q6rPs7PVMt234EFJejcWOVVt/iawPskpTtvoBq/M+d9JvfNRrbd3rqlOUC5gGyhBKeg1J01VZ7X9Nh3zXuzjqZ127TGl2ce6yit6Wbdv5Prvy23obmTe5htW6z1XeBA5nN7lb4k823q+dZcb9NifSTTm7q8odqeyHO5Wc/y6vgsrbanvnPpvjtbWG3TZkpQbfZdUOrJM5Rzsbu+NefE1XQaXw9V5ejex82667qxkM75fCflwhyZx89R4thGykXo5ZR41jQwBimx65TM42coF7S/y2N2eM67OPfjhizzhZQGVtOtt4ISO5rXUmCfyW7pb66GByitjGnAMxExFzgB+FFE/Czlqvh5SstiIXAY5UAeTalwdT7Tq/HNuey1wEBE7EUJlJ+ntPb/jbIjn42Iiyn9rYOUK+zP0blVPCPzG6RU7rplqRx+P51KdjudH47bI9MPzuW/SKc18TTw6Rz+1yxL0/0ySDkB5lIucFBOvuYkfSHlaj6YZTg49+HmnP8pyklQt9BEubDulsPfpHMSKedvTqyTM+8Lc9mmvM3dQRPQm/1CtS/+Px0n0bl43lDNt4HOHQx0grQolb65wN1JqbRQ6kew7THuPunWU+7+puXyV2T6HpQ7t3+j1J3pOV9T9qWUO4cBSjAISstqkE4raR2dYPPl3BfNHU5zd7GWzsXiO2zrceAldO5IZlCCT9M9Ap3g2tyhHZ7r2L3aT79FaSUCzKU8f2q2YwOd4DeDTkt/N0pdINe/b873u3TOxdm5X5TbcWumz8n3upGymnLhbtIfpASiprU7J8vfXKSWZRl3o+zr9ZkHlHq0qcqLnLcpS5N+Q6YFpXW7uNqetXRa42+u9pXo3EH8KJfdi3LH33TfNvsbOnWsqfNkmZsfMPs45Vipmr6UcoFo7gKPp3SHraWcs4267jbH68TM/7uUY9XcBb2Tbb8o25xrA5TjeA2lkdbcbU6jUxeb8aMjYm6+DomIbR5u0zXzpIiItcCjkn6TclLsK+lVlOD0S5SW+yClq+YhStfHhq5sfgw0n2DZi7Lj5gJbM9+bKSfN64BFlAO4f37q5VDK7dJGSvfHVsrBvifTZlCeJTQVs1lHUA7AIGX/zaA8vAN4C50gqCzPvjnfQG4DlBNonyzTvpRgIEkfzXmnUQJg4wV0TowtlO6y5qLzMjrdGdPz/cBc/9Is33OUE7MJtE03yUbKBaRJawLoYOZZ/35SE1Dele/TMt8zqn10GJ0L+ppqvkfpnGhbKMGwOZGakzWAnwIOqrb5P+U6jgX2z22r62zT0p+WeRyW77vn+6Fs+1yl6WqbTqdF+BydiyWU22goF43GTEpdgFIHV+c6X0i56IpSD5tnBlDqwSBl/385016c74fm+6bcpuaEb+6i9shl96fcBTfH4aose3Mc64v4AJ3AvI7OnU0T7GZQGhEzACLiT3Ldr6KcX2+ulm0uOk19OoDSUGkuoDPzvem+ahoczcWwDmBH5jbtV6U18yHpJDrB9wXV9FfRqZdH0bkYiXIHuEeOv5VOcF+dZWnWKzrdts2+mlYtu2f13gT6+sJzPKVONeNQjkXzLATKefzjzGMPOt2Ykftrr3zdQ+mq24uyj5+j1PVnKb0bUII/lPqxIaeJTvf0IXRspsQOKBfI9zcTJM1lODuoe6f+VMSHgPNy+DBKK7zpO1tO6Ub4AKXSrqC01j5IuZI+Lx9K984A5fbpWjr9wutymaZluAq4I/NtWpdNq/S7uf7mlqu5nev1kC8orbg6vQkgzQnQ3Co+Red2vL6d30yn77wJSPWDsMEsT/Pwqnn402xH87Cy10Onb9Pp2rgsp/+ATqVvHkA14003UVOu7od9zTK/S6cfvr7d7+dB95N0HrgFpdXW3ZU0UOXZtPybrpOmD7XpJlhF6Z55NLdtVVWm5mLWq+voL6vxpkthC50+9+756+6Sh7qmNw8j6y6I9cBX6HSTNF0ad9G5I4hqXc3DvuZBYFMnH6A8yKvXN0hpJNxVbduz1fSNdLpoBug8gG3qzXNsWw/qh4n1vm8oT/IAAAHYSURBVGouRHU9qB+6bgH+uittK+W8a45Psy3ru45FXX/qbqPmmUyd3xM8/wFyUz9+WOVZd1tG17qaffH9HuXYSuc8aZ75RO7jVV15due9mU5XatM12DwXuj+3bXMew2a+xXQe5m6mPAfYlK8HKBeOL+c8yyi9AjNzf62iNFgfzfz+mhL/rsh1XExpENybeX1mUj+9swMuKu+kPMzZG1gAHLWd+UwH9szhI3MHNz8W95XcsaeN9aK3A/bHwXlSTMuK8fFxzHuffBel3/EPhplnN0pr9607uD5Mo3QRHbEj1zsO5b4eOHYS1tscrxdTukR+ahTL7p3LvGiI6Yspv/fezLuA0mq/nCE+UjxM+Yasc1P5xTh+XHe8XhP2H7k7gqRfp1SE5ZTukPkRcefwSw1pb+DbkmbQud1fQLmSH0C51T57zIWeQPkFofOB/0HpBzycTtfTePgdSadQLoZ3AZ/tMc95+eWsPSm3nV/uMc+EyC/HXA9cGxEPjzT/VCBpP0pL9J6IuGmk+SfA9VmG3SkNhCdHWgAgj/GllE+NrBlm1gtVvpi4J3l+Shpm9ufpp87ZKPgH18zMWmRK/AyDmZntGA76ZmYt4qBvZtYiDvpmZi3ioG9m1iL/DvynEX2UvXnQAAAAAElFTkSuQmCC\n",
            "text/plain": [
              "<Figure size 432x288 with 1 Axes>"
            ]
          },
          "metadata": {
            "needs_background": "light"
          }
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "KMkwFyb-xoIY"
      },
      "source": [
        "# 5. Удалите 2 любых не нужных на ваш вгляд столбца\n",
        "\n",
        "# ваш код тут"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 419
        },
        "id": "sR1uCpmWm9-4",
        "outputId": "e0a366f7-2c1f-42e9-f1a5-a3e1b4856026"
      },
      "source": [
        "df.drop(['Unnamed: 0'], axis = 1)\n",
        "df.drop(['vin'], axis = 1)"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>Unnamed: 0</th>\n",
              "      <th>price</th>\n",
              "      <th>brand</th>\n",
              "      <th>model</th>\n",
              "      <th>year</th>\n",
              "      <th>title_status</th>\n",
              "      <th>mileage</th>\n",
              "      <th>color</th>\n",
              "      <th>lot</th>\n",
              "      <th>state</th>\n",
              "      <th>country</th>\n",
              "      <th>condition</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>0</td>\n",
              "      <td>6300</td>\n",
              "      <td>toyota</td>\n",
              "      <td>cruiser</td>\n",
              "      <td>2008</td>\n",
              "      <td>clean vehicle</td>\n",
              "      <td>274117.0</td>\n",
              "      <td>black</td>\n",
              "      <td>159348797</td>\n",
              "      <td>new jersey</td>\n",
              "      <td>usa</td>\n",
              "      <td>10 days left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>1</td>\n",
              "      <td>2899</td>\n",
              "      <td>ford</td>\n",
              "      <td>se</td>\n",
              "      <td>2011</td>\n",
              "      <td>clean vehicle</td>\n",
              "      <td>190552.0</td>\n",
              "      <td>silver</td>\n",
              "      <td>166951262</td>\n",
              "      <td>tennessee</td>\n",
              "      <td>usa</td>\n",
              "      <td>6 days left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>2</td>\n",
              "      <td>5350</td>\n",
              "      <td>dodge</td>\n",
              "      <td>mpv</td>\n",
              "      <td>2018</td>\n",
              "      <td>clean vehicle</td>\n",
              "      <td>39590.0</td>\n",
              "      <td>silver</td>\n",
              "      <td>167655728</td>\n",
              "      <td>georgia</td>\n",
              "      <td>usa</td>\n",
              "      <td>2 days left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>3</td>\n",
              "      <td>25000</td>\n",
              "      <td>ford</td>\n",
              "      <td>door</td>\n",
              "      <td>2014</td>\n",
              "      <td>clean vehicle</td>\n",
              "      <td>64146.0</td>\n",
              "      <td>blue</td>\n",
              "      <td>167753855</td>\n",
              "      <td>virginia</td>\n",
              "      <td>usa</td>\n",
              "      <td>22 hours left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>4</td>\n",
              "      <td>27700</td>\n",
              "      <td>chevrolet</td>\n",
              "      <td>1500</td>\n",
              "      <td>2018</td>\n",
              "      <td>clean vehicle</td>\n",
              "      <td>6654.0</td>\n",
              "      <td>red</td>\n",
              "      <td>167763266</td>\n",
              "      <td>florida</td>\n",
              "      <td>usa</td>\n",
              "      <td>22 hours left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>...</th>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2494</th>\n",
              "      <td>2494</td>\n",
              "      <td>7800</td>\n",
              "      <td>nissan</td>\n",
              "      <td>versa</td>\n",
              "      <td>2019</td>\n",
              "      <td>clean vehicle</td>\n",
              "      <td>23609.0</td>\n",
              "      <td>red</td>\n",
              "      <td>167722715</td>\n",
              "      <td>california</td>\n",
              "      <td>usa</td>\n",
              "      <td>1 days left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2495</th>\n",
              "      <td>2495</td>\n",
              "      <td>9200</td>\n",
              "      <td>nissan</td>\n",
              "      <td>versa</td>\n",
              "      <td>2018</td>\n",
              "      <td>clean vehicle</td>\n",
              "      <td>34553.0</td>\n",
              "      <td>silver</td>\n",
              "      <td>167762225</td>\n",
              "      <td>florida</td>\n",
              "      <td>usa</td>\n",
              "      <td>21 hours left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2496</th>\n",
              "      <td>2496</td>\n",
              "      <td>9200</td>\n",
              "      <td>nissan</td>\n",
              "      <td>versa</td>\n",
              "      <td>2018</td>\n",
              "      <td>clean vehicle</td>\n",
              "      <td>31594.0</td>\n",
              "      <td>silver</td>\n",
              "      <td>167762226</td>\n",
              "      <td>florida</td>\n",
              "      <td>usa</td>\n",
              "      <td>21 hours left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2497</th>\n",
              "      <td>2497</td>\n",
              "      <td>9200</td>\n",
              "      <td>nissan</td>\n",
              "      <td>versa</td>\n",
              "      <td>2018</td>\n",
              "      <td>clean vehicle</td>\n",
              "      <td>32557.0</td>\n",
              "      <td>black</td>\n",
              "      <td>167762227</td>\n",
              "      <td>florida</td>\n",
              "      <td>usa</td>\n",
              "      <td>2 days left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2498</th>\n",
              "      <td>2498</td>\n",
              "      <td>9200</td>\n",
              "      <td>nissan</td>\n",
              "      <td>versa</td>\n",
              "      <td>2018</td>\n",
              "      <td>clean vehicle</td>\n",
              "      <td>31371.0</td>\n",
              "      <td>silver</td>\n",
              "      <td>167762228</td>\n",
              "      <td>florida</td>\n",
              "      <td>usa</td>\n",
              "      <td>21 hours left</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "<p>2499 rows × 12 columns</p>\n",
              "</div>"
            ],
            "text/plain": [
              "      Unnamed: 0  price      brand  ...       state  country      condition\n",
              "0              0   6300     toyota  ...  new jersey      usa   10 days left\n",
              "1              1   2899       ford  ...   tennessee      usa    6 days left\n",
              "2              2   5350      dodge  ...     georgia      usa    2 days left\n",
              "3              3  25000       ford  ...    virginia      usa  22 hours left\n",
              "4              4  27700  chevrolet  ...     florida      usa  22 hours left\n",
              "...          ...    ...        ...  ...         ...      ...            ...\n",
              "2494        2494   7800     nissan  ...  california      usa    1 days left\n",
              "2495        2495   9200     nissan  ...     florida      usa  21 hours left\n",
              "2496        2496   9200     nissan  ...     florida      usa  21 hours left\n",
              "2497        2497   9200     nissan  ...     florida      usa    2 days left\n",
              "2498        2498   9200     nissan  ...     florida      usa  21 hours left\n",
              "\n",
              "[2499 rows x 12 columns]"
            ]
          },
          "metadata": {},
          "execution_count": 23
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "9gYsDYydxwPM"
      },
      "source": [
        "# 6. Замените значения в столбце title_status на числовые\n",
        "# Например, clean vehicle станет равным 0 и т д.\n",
        "\n",
        "# ваш код тут"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 419
        },
        "id": "l_KO2lhxnZEp",
        "outputId": "8a2e442c-4f0c-40bd-d12c-b8520f7c0988"
      },
      "source": [
        "from sklearn.preprocessing import LabelEncoder\n",
        "\n",
        "labelencoder = LabelEncoder()\n",
        "df['title_status'] = labelencoder.fit_transform(df['title_status'])\n",
        "df"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>Unnamed: 0</th>\n",
              "      <th>price</th>\n",
              "      <th>brand</th>\n",
              "      <th>model</th>\n",
              "      <th>year</th>\n",
              "      <th>title_status</th>\n",
              "      <th>mileage</th>\n",
              "      <th>color</th>\n",
              "      <th>vin</th>\n",
              "      <th>lot</th>\n",
              "      <th>state</th>\n",
              "      <th>country</th>\n",
              "      <th>condition</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>0</td>\n",
              "      <td>6300</td>\n",
              "      <td>toyota</td>\n",
              "      <td>cruiser</td>\n",
              "      <td>2008</td>\n",
              "      <td>0</td>\n",
              "      <td>274117.0</td>\n",
              "      <td>black</td>\n",
              "      <td>jtezu11f88k007763</td>\n",
              "      <td>159348797</td>\n",
              "      <td>new jersey</td>\n",
              "      <td>usa</td>\n",
              "      <td>10 days left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>1</td>\n",
              "      <td>2899</td>\n",
              "      <td>ford</td>\n",
              "      <td>se</td>\n",
              "      <td>2011</td>\n",
              "      <td>0</td>\n",
              "      <td>190552.0</td>\n",
              "      <td>silver</td>\n",
              "      <td>2fmdk3gc4bbb02217</td>\n",
              "      <td>166951262</td>\n",
              "      <td>tennessee</td>\n",
              "      <td>usa</td>\n",
              "      <td>6 days left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>2</td>\n",
              "      <td>5350</td>\n",
              "      <td>dodge</td>\n",
              "      <td>mpv</td>\n",
              "      <td>2018</td>\n",
              "      <td>0</td>\n",
              "      <td>39590.0</td>\n",
              "      <td>silver</td>\n",
              "      <td>3c4pdcgg5jt346413</td>\n",
              "      <td>167655728</td>\n",
              "      <td>georgia</td>\n",
              "      <td>usa</td>\n",
              "      <td>2 days left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>3</td>\n",
              "      <td>25000</td>\n",
              "      <td>ford</td>\n",
              "      <td>door</td>\n",
              "      <td>2014</td>\n",
              "      <td>0</td>\n",
              "      <td>64146.0</td>\n",
              "      <td>blue</td>\n",
              "      <td>1ftfw1et4efc23745</td>\n",
              "      <td>167753855</td>\n",
              "      <td>virginia</td>\n",
              "      <td>usa</td>\n",
              "      <td>22 hours left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>4</td>\n",
              "      <td>27700</td>\n",
              "      <td>chevrolet</td>\n",
              "      <td>1500</td>\n",
              "      <td>2018</td>\n",
              "      <td>0</td>\n",
              "      <td>6654.0</td>\n",
              "      <td>red</td>\n",
              "      <td>3gcpcrec2jg473991</td>\n",
              "      <td>167763266</td>\n",
              "      <td>florida</td>\n",
              "      <td>usa</td>\n",
              "      <td>22 hours left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>...</th>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2494</th>\n",
              "      <td>2494</td>\n",
              "      <td>7800</td>\n",
              "      <td>nissan</td>\n",
              "      <td>versa</td>\n",
              "      <td>2019</td>\n",
              "      <td>0</td>\n",
              "      <td>23609.0</td>\n",
              "      <td>red</td>\n",
              "      <td>3n1cn7ap9kl880319</td>\n",
              "      <td>167722715</td>\n",
              "      <td>california</td>\n",
              "      <td>usa</td>\n",
              "      <td>1 days left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2495</th>\n",
              "      <td>2495</td>\n",
              "      <td>9200</td>\n",
              "      <td>nissan</td>\n",
              "      <td>versa</td>\n",
              "      <td>2018</td>\n",
              "      <td>0</td>\n",
              "      <td>34553.0</td>\n",
              "      <td>silver</td>\n",
              "      <td>3n1cn7ap5jl884088</td>\n",
              "      <td>167762225</td>\n",
              "      <td>florida</td>\n",
              "      <td>usa</td>\n",
              "      <td>21 hours left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2496</th>\n",
              "      <td>2496</td>\n",
              "      <td>9200</td>\n",
              "      <td>nissan</td>\n",
              "      <td>versa</td>\n",
              "      <td>2018</td>\n",
              "      <td>0</td>\n",
              "      <td>31594.0</td>\n",
              "      <td>silver</td>\n",
              "      <td>3n1cn7ap9jl884191</td>\n",
              "      <td>167762226</td>\n",
              "      <td>florida</td>\n",
              "      <td>usa</td>\n",
              "      <td>21 hours left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2497</th>\n",
              "      <td>2497</td>\n",
              "      <td>9200</td>\n",
              "      <td>nissan</td>\n",
              "      <td>versa</td>\n",
              "      <td>2018</td>\n",
              "      <td>0</td>\n",
              "      <td>32557.0</td>\n",
              "      <td>black</td>\n",
              "      <td>3n1cn7ap3jl883263</td>\n",
              "      <td>167762227</td>\n",
              "      <td>florida</td>\n",
              "      <td>usa</td>\n",
              "      <td>2 days left</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2498</th>\n",
              "      <td>2498</td>\n",
              "      <td>9200</td>\n",
              "      <td>nissan</td>\n",
              "      <td>versa</td>\n",
              "      <td>2018</td>\n",
              "      <td>0</td>\n",
              "      <td>31371.0</td>\n",
              "      <td>silver</td>\n",
              "      <td>3n1cn7ap4jl884311</td>\n",
              "      <td>167762228</td>\n",
              "      <td>florida</td>\n",
              "      <td>usa</td>\n",
              "      <td>21 hours left</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "<p>2499 rows × 13 columns</p>\n",
              "</div>"
            ],
            "text/plain": [
              "      Unnamed: 0  price      brand  ...       state  country      condition\n",
              "0              0   6300     toyota  ...  new jersey      usa   10 days left\n",
              "1              1   2899       ford  ...   tennessee      usa    6 days left\n",
              "2              2   5350      dodge  ...     georgia      usa    2 days left\n",
              "3              3  25000       ford  ...    virginia      usa  22 hours left\n",
              "4              4  27700  chevrolet  ...     florida      usa  22 hours left\n",
              "...          ...    ...        ...  ...         ...      ...            ...\n",
              "2494        2494   7800     nissan  ...  california      usa    1 days left\n",
              "2495        2495   9200     nissan  ...     florida      usa  21 hours left\n",
              "2496        2496   9200     nissan  ...     florida      usa  21 hours left\n",
              "2497        2497   9200     nissan  ...     florida      usa    2 days left\n",
              "2498        2498   9200     nissan  ...     florida      usa  21 hours left\n",
              "\n",
              "[2499 rows x 13 columns]"
            ]
          },
          "metadata": {},
          "execution_count": 43
        }
      ]
    }
  ]
}
