# -*- coding: utf-8 -*-
"""class_work_1_Kulikov

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fHlluj5PDIOu8gHGSI0p9jOHDCocezyW
"""

name = ['m', 'a', 'x', 'i', 'm', 'i', 'l', 'i', 'a', 'n', 16]
#1е задание
print(name[1:len(name)-1])
#2е задание
name.append('10П')
print(name)
#3е задание
surname = list('kulikov')
ns = name+surname
print(ns)