# -*- coding: utf-8 -*-
"""class_work_5_Klenovskaya.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xlnaAI2fnh5L_COhGJSGv3reyTFX6fes
"""



import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print('Задание 1')
def distance(x1, x2, y1, y2):
  return math.hypot(x2-x1, y2-y1)
x1= float(input())
x2= float(input())
y1= float(input())
y2= float(input())
print(distance(x1, x2, y1, y2))


print('Задание 2')
a=[2,4,6,31,76,83]
b=[1,3,6,8,99,100]
c=[]
for i in range(len(a)):
  if int(a[i])%2==0:
    c.append(int(a[i])*int(b[i]))
  elif int(a[i])%2==1:
    c.append(int(a[i])+int(b[i]))
  print(*c)


print('Задание 3')
x = np.array([6, 8, 1, 3, 0, 4, 1, 7, 0])
x_maksimum=8
for i in range(len(x)-1):
  if x[i+1]==0 and x[i]!=0 and x[i]<x_maksimum:
     x_maksimum=x[i]
print(x_maksimum)

print("Задание 4")
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("income_evaluation.csv.zip")
df.head()
print('4.1')
df[' education'].value_counts()
print('4.2')
sr_age=df['age'].mean()
print(sr_age)
print('4.3')
x= ['Female', 'Male']
y= [len(df[df[' sex']=='Female']), len(df[df[' sex']=='Male'])]
fig, ax = plt.subplots()
ax.bar(x,y)
plt.show()