# -*- coding: utf-8 -*-
"""class_work_5_Kulikov

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qnehiG6HLb2exTPVmDamD6pwgMQgsQv8

Задание 1
"""

import math
def distance(x1, y1, x2, y2):
  x1 = int(x1)
  x2 = int(x2)
  y1 = int(y1)
  y2 = int(y2)
  x = x2 - x1
  y = y2 - y1
  print(math.sqrt(x*x + y*y))
x1, y1, x2, y2 = input().split(' ')
distance(x1, y1, x2, y2)

"""Задание 2"""

a = list(input().split(' '))
b = list(input().split(' '))
c = b
for i in range(len(a)):
  if int(a[i]) % 2 == 0:
    c[i] = int(a[i]) * int(b[i])
  else:
    c[i] = int(a[i]) + int(b[i])
print(c)

"""Задание 3"""

import numpy as np
x = np.array([6, 2, 0, 3, 0, 0, 1, 7, 0])
xmn = 7 # максимальный элемент в векторе
for i in range(len(x) - 1):
  if x[i + 1] == 0 and x[i] < xmn and x[i] != 0:
    xmn = x[i]
print(xmn)

"""Задание 4"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
bach = 0
hs = 0
th = 0
ass = 0
tag = 0
df = pd.read_csv("income_evaluation.csv")

# 1й подпункт
for i in range(len(df)):
  if df[' education'][i] == ' Bachelors':
    bach += 1
  if df[' education'][i] == ' HS-grad':
    hs += 1
  if df[' education'][i] == ' 11th':
    th += 1
  if df[' education'][i] == ' Assoc-acdm':
    ass += 1
print('Бакалавры:',bach)
print('HS-grad:',hs)
print('Одиннадцатый класс:', th)
print('Академик:', ass)

# 2й подпункт
for j in range(len(df)):
  tag += int(df.age[j])
print('Средний возраст:', tag/int(len(df)))

# 3й подпункт (что значит распределение мужчин и женщин?)

# 4й подпункт
df.drop(df[df[' income'] == ' >50K'].index, inplace=True)
df

"""Задание 5"""

agemx = 0
for i in range(len(df)):
  if (str(df[' race'][i]) == ' White') and (int(df.age[i]) > agemx):
    agemx = df.age[i]
print(agemx)