# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wq8FSLs7QXbYy0UpH9hqwmdbgmCNcRxR
"""

from google.colab import files
uploaded = files.upload()
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Wine = pd.read_csv('Wine.csv')
Wine

X = Wine.iloc[:,:-1]
X

from scipy.cluster.hierarchy import dendrogram, linkage
from matplotlib import pyplot as plt
Z = linkage(X, 'ward')

fig = plt.figure(figsize=(10, 10))
dn = dendrogram(Z)

from scipy.cluster.hierarchy import linkage

Z = linkage(X, method='average', metric='euclidean')
Z[0]

Z[160]

from scipy.cluster.hierarchy import fcluster
label = fcluster(Z, 10, criterion='distance')

np.unique(label)
label

Wine['clasters'] = label
Wine

plt.scatter(Wine.loc[label==1, 'Color_Intensity'], Wine.loc[label==1, 'Alcohol'], s=10, marker='o', color='red')
plt.scatter(Wine.loc[label==2, 'Color_Intensity'], Wine.loc[label==2, 'Alcohol'], s=10, marker='o', color='blue')
plt.scatter(Wine.loc[label==3, 'Color_Intensity'], Wine.loc[label==3, 'Alcohol'], s=10, marker='o', color='green')
plt.scatter(Wine.loc[label==4, 'Color_Intensity'], Wine.loc[label==4, 'Alcohol'], s=10, marker='o', color='magenta')
plt.show()

from sklearn.cluster import AgglomerativeClustering

hc = AgglomerativeClustering(n_clusters = 4, affinity = 'euclidean', linkage = 'ward')

y_hc = hc.fit_predict(X)
y_hc

X['clasters'] = y_hc
X

plt.scatter(X.loc[y_hc==0, 'Alcohol'], X.loc[y_hc==0, 'Color_Intensity'], s=10, marker='o', color='red')
plt.scatter(X.loc[y_hc==1, 'Alcohol'], X.loc[y_hc==1, 'Color_Intensity'], s=10, marker='o', color='blue')
plt.scatter(X.loc[y_hc==2, 'Alcohol'], X.loc[y_hc==2, 'Color_Intensity'], s=10, marker='o', color='green')
plt.scatter(X.loc[y_hc==3, 'Alcohol'], X.loc[y_hc==3, 'Color_Intensity'], s=10, marker='o', color='magenta')
plt.show()