# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RMFZ_wKTgFBu7tZvpfD5b-Akw_7aNR8V
"""

def distance(x1,y1,x2,y2):
  a=((x2-x1)**2+(y2-y1)**2)**0.5
  print(a)
distance(int(input()),int(input()),int(input()),int(input()))

def season(month):
  if month>0 and month<3 or  month==12:
    print('Зима')
  elif month>=3 and month<=5:
    print('Весна')
  elif month>=6 and month<=8:
    print('Лето')
  elif month>=9 and month<=11:
    print('Осень')

season(int(input()))

def is_prime(a):
  for i in range(2,a):
    if a%i==0:
      b=False
      #print(b)
      break
    else:
      b=True
  print(b)

is_prime(int(input()))

def list_reverse(a):
  a = a[::-1]
  print(a)
list_reverse(list(map(int,input().split())))

a = "Привет мир!"
a = a[3:8].upper()
print(a)

x = list(map(int,input().split()))
u = []
for i in range(0,len(x)):
  if x.index(i)%2==0:
    u.insert(i,x[i])
  else:
    u.insert(i,x[-i])
print(u)

for i in range(0,501):
  p=i
  o=0
  if i%7==0:
    while p!=0:
      o=o+1
      p=p//10
    p=i
    for i1 in range(0,o):
      if (p%10==8):
        print(i)
        break
      p=p//10

def more_than_five(lst):
  for i in range(0,len(lst)):
    if abs(lst[i])>10:
      lst1.append(lst[i])
  print(lst1)
lst1=[]
more_than_five(list(map(int,input().split())))