# -*- coding: utf-8 -*-
"""Home_work_6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zCx-L_oSqD6C1F3nH8hl28F8mezo1DEH
"""



from google.colab import files
uploaded = files.upload()
import numpy as np
from sklearn.cluster import KMeans
import pandas as pd
Wine = pd.read_csv('Wine.csv')
Wine.head()

Wine.info(memory_usage='deep')
Wine=Wine.dropna()

import matplotlib.pyplot as plt
X = Wine.loc[:,['Alcohol','Color_Intensity']]
Y = Wine['Customer_Segment']
SSE = [] # Сумма квадратов ошибок для каждого результата

for k in range(1,9):
    kmeans = KMeans(n_clusters = k) # построить кластер
    kmeans.fit(X)
    SSE.append(kmeans.inertia_)
 
plt.plot(range(1,9), SSE, marker='s');
plt.xlabel('k')
plt.ylabel('SSE');
plt.show()

kmeans = KMeans(n_clusters=4)
kmeans.fit(X)
Y_pred = kmeans.labels_
X['Customer_Segment'] = Y_pred
X[X['Customer_Segment']==0]
X

import matplotlib.pyplot as plt
plt.plot(X[X['Customer_Segment']==0]['Alcohol'], X[X['Customer_Segment']==0]['Color_Intensity'], 'bo', label='class1')
plt.plot(X[X['Customer_Segment']==1]['Alcohol'], X[X['Customer_Segment']==1]['Color_Intensity'], 'go', label='class2')
plt.plot(X[X['Customer_Segment']==2]['Alcohol'], X[X['Customer_Segment']==2]['Color_Intensity'], 'ro', label='class3')
plt.plot(X[X['Customer_Segment']==3]['Alcohol'], X[X['Customer_Segment']==3]['Color_Intensity'], 'mo', label='class4')
plt.legend(loc=0)
plt.xlabel('Color_Intensity	')
plt.ylabel('Alcohol')
plt.show()

